#!/bin/bash

## Define and initialize test-result specific variables.
app_deploy_rc_val=1
csi_vol_resize_rc_val=1
zv_properties_verify_rc_val=1

## SSH into the cluster to run the kubernetes jobs for the experiments
connect_cluster() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port -o LogLevel=ERROR 'cd e2e-nativek8s && bash openebs-nativek8s/pipelines/stages/3-functional/3F05-zfs-volume-resize-xfs run_job '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'

}

#######################################
# Deploy percona application on ZFSPV #
#######################################

app_deploy() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

## Pooling over the previous job to wait for its completion
bash openebs-nativek8s/utils/pooling jobname:zfspv-custom-topology
bash openebs-nativek8s/utils/e2e-cr jobname:zfs-volume-resize-xfs jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

## Generate the test name for running the litmusbook for percona deployment
run_id="xfs";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=percona-deployment metadata=${run_id})
echo $test_name

## copy the content of provisioner run_litmus_test.yml into a temporary file to update the test specific parameters.
cd e2e-tests
cp apps/percona/deployers/run_litmus_test.yml deploy_percona_zfspv_xfs.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/app: percona-deployment/app: deploy-percona-xfs/g' \
-e 's/generateName: litmus-percona-/generateName: litmus-percona-xfs-/g' \
-e 's/value: openebs-standard/value: zfs-sc-xfs/g' \
-e '/name: TARGET_AFFINITY_CHECK/{n;s/value: enable/value: disable/g}' \
-e 's/value: app-percona-ns/value: percona-xfs/g' deploy_percona_zfspv_xfs.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' deploy_percona_zfspv_xfs.yml

cat deploy_percona_zfspv_xfs.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='app:deploy-percona-xfs' job=deploy_percona_zfspv_xfs.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfs-volume-resize-xfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_deploy_rc_val=$(echo $?)
if [ "$app_deploy_rc_val" != "0" ]; then
exit 1;
fi

}

#############################
#  ZVOL-properties-verify   #
#############################

zv_properties_verify() {

## Generate the test name for running the litmusbook for percona deployment
run_id="xfs";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=zvol-properties-verify metadata=${run_id})
echo $test_name

## copy the content of run_litmus_test.yml into a temporary file to update the test specific parameters.
cd e2e-tests
cp experiments/zfs-localpv/functional/zv-properties-verify/run_litmus_test.yml zv_properties_xfs.yml

# Modify test specific values in runner file using sed command
sed -i -e '/name: APP_NAMESPACE/{n;s/.*/            value: percona-xfs/g}' \
-e '/name: APP_PVC/{n;s/.*/            value: percona-mysql-claim/g}' \
-e '/name: OPERATOR_NAMESPACE/{n;s/.*/            value: openebs/g}' \
-e 's/generateName: zv-properties-verify-/generateName: xfs-zv-properties-verify-/g' \
-e 's/name: zv-properties-verify/name: zv-properties-verify-xfs/g' zv_properties_xfs.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' zv_properties_xfs.yml

cat zv_properties_xfs.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='name:zv-properties-verify-xfs' job=zv_properties_xfs.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfs-volume-resize-xfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

zv_properties_verify_rc_val=$(echo $?)
if [ "$zv_properties_verify_rc_val" != "0" ]; then
csi_vol_resize
app_deprovision
fi

}

#############################
# CSI volume resize for xfs #
#############################

csi_vol_resize() {

## Generate the test name for running the litmusbook for percona deployment
run_id="xfs";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=csi-volume-resize metadata=${run_id})
echo $test_name

## copy the content of run_litmus_test.yml into a temporary file to update the test specific parameters.
cd e2e-tests
cp experiments/functional/csi-volume-resize/run_litmus_test.yml csi_vol_resize_xfs.yml

# Modify test specific values in runner file using sed command
sed -i -e '/name: APP_PVC/{n;s/.*/            value: percona-mysql-claim/g}' \
-e '/name: APP_LABEL/{n;s/.*/            value: name=percona/g}' \
-e '/name: STORAGE_CLASS/{n;s/.*/            value: zfs-sc-xfs/g}' \
-e 's/app: csi-vol-resize/app: csi-vol-resize-xfs/g' \
-e '/name: PV_CAPACITY/{n;s/.*/            value: 5Gi/g}' \
-e '/name: NEW_CAPACITY/{n;s/.*/            value: 10Gi/g}' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: percona-xfs/g}' csi_vol_resize_xfs.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' csi_vol_resize_xfs.yml

cat csi_vol_resize_xfs.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='app:csi-vol-resize-xfs' job=csi_vol_resize_xfs.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfs-volume-resize-xfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

csi_vol_resize_rc_val=$(echo $?)
if [ "$csi_vol_resize_rc_val" != "0" ]; then
app_deprovision
fi

}

#######################################
#   Deprovision percona application   #
#######################################

app_deprovision() {

## Generate test name for running litmusbook for generate load on application
run_id="xfs-deprovision";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=percona-deployment metadata=${run_id})
echo $test_name

# copy the content of workload run_litmus_test.yml into a temporary file to update the test specific parameters.
cd e2e-tests
cp apps/percona/deployers/run_litmus_test.yml deprovision_percona_zfspv_xfs.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/app: percona-deployment/app: deprovision-percona-xfs/g' \
-e 's/generateName: litmus-percona-/generateName: litmus-percona-xfs-dep-/g' \
-e 's/value: openebs-standard/value: zfs-sc-xfs/g' \
-e 's/value: provision/value: deprovision/g' \
-e '/name: TARGET_AFFINITY_CHECK/{n;s/value: enable/value: disable/g}' \
-e 's/value: app-percona-ns/value: percona-xfs/g' deprovision_percona_zfspv_xfs.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' deprovision_percona_zfspv_xfs.yml           

cat deprovision_percona_zfspv_xfs.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='app:deprovision-percona-xfs' job=deprovision_percona_zfspv_xfs.yml
cd ..
## Get the cluster state Once the litmus jobs completed.
bash openebs-nativek8s/utils/dump_cluster_state;
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfs-volume-resize-xfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_deprovision_rc_val=$(echo $?)

if [ "$app_deprovision_rc_val" -eq "0" ] &&
   [ "$zv_properties_verify_rc_val" -eq "0" ] &&
   [ "$csi_vol_resize_rc_val" -eq "0" ] &&
   [ "$app_deploy_rc_val" -eq "0" ]; then

## Update the e2e-result-custom-resources for the job
bash openebs-nativek8s/utils/e2e-cr jobname:zfs-volume-resize-xfs jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Pass
python3 openebs-nativek8s/utils/result/result_update.py $job_id 3F05 3-functional "zv property verify and zfs volume resize when fstype is xfs" Pass $pipeline_id "$current_time" $commit_id $gittoken

else
## Update the e2e-result-custom-resources for the job
bash openebs-nativek8s/utils/e2e-cr jobname:zfs-volume-resize-xfs jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Fail
python3 openebs-nativek8s/utils/result/result_update.py $job_id 3F05 3-functional "zv property verify and zfs volume resize when fstype is xfs" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

}

if [ "$1" == "run_job" ];then
  app_deploy $2 $3 $4
  zv_properties_verify
  csi_vol_resize
  app_deprovision
else
  connect_cluster
fi

