#!/bin/bash

## Define and initialize test-result specific variables.
app_deploy_btrfs_rc_val=1
app_loadgen_btrfs_rc_val=1
zfspv_snapshot_btrfs_rc_val=1
zfspv_clone_btrfs_rc_val=1
zfspv_clone_btrfs_deprovision_rc_val=1
zfspv_snapshot_btrfs_deprovision_rc_val=1

## SSH into the cluster to run the kubernetes jobs for the experiments
connect_cluster() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port -o LogLevel=ERROR 'cd e2e-nativek8s && bash openebs-nativek8s/pipelines/stages/3-functional/3F13-zfspv-snapshot-clone-btrfs-create run_job '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'

}

###########################################################
# Deploy percona application on ZFSPV when fstype is btrfs #
###########################################################

app_deploy_btrfs() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

## Pooling over the previous job to wait for its completion
bash openebs-nativek8s/utils/pooling jobname:zfspv-custom-topology
bash openebs-nativek8s/utils/e2e-cr jobname:zfspv-snapshot-clone-btrfs-create jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

## Generate the test name for running the litmusbook for percona deployment
run_id="btrfs-snap-clone";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=percona-deployment metadata=${run_id})
echo $test_name
cd e2e-tests

# copy the content of deployers run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/percona/deployers/run_litmus_test.yml percona_btrfs_snap_clone.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/app: percona-deployment/app: snap-clone-btrfs/g' \
-e 's/generateName: litmus-percona-/generateName: percona-btrfs-snap-clone-/g' \
-e 's/value: openebs-standard/value: zfs-sc-btrfs/g' \
-e '/name: TARGET_AFFINITY_CHECK/{n;s/value: enable/value: disable/g}' \
-e 's/value: app-percona-ns/value: snap-clone-btrfs/g' percona_btrfs_snap_clone.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' percona_btrfs_snap_clone.yml

cat percona_btrfs_snap_clone.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='app:snap-clone-btrfs' job=percona_btrfs_snap_clone.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfspv-snapshot-clone-btrfs-create $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_deploy_btrfs_rc_val=$(echo $?)
if [ "$app_deploy_btrfs_rc_val" != "0" ]; then
exit 1;
fi

}

###################################
# Loadgen on Percona application  #
###################################

app_loadgen_btrfs() {

## Generate test name for running litmusbook for generate load on application
run_id="btrfs-snap-clone";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=percona-loadgen metadata=${run_id})
echo $test_name
cd e2e-tests

# copy the content of workload run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/percona/workload/run_litmus_test.yml loadgen_btrfs_snap_clone.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/loadgen: percona-loadjob/loadgen: snap-clone-btrfs/g' \
-e 's/generateName: percona-loadgen-/generateName: percona-loadgen-btrfs-snap-clone-/g' \
-e 's/value: app-percona-ns/value: snap-clone-btrfs/g' loadgen_btrfs_snap_clone.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' loadgen_btrfs_snap_clone.yml

cat loadgen_btrfs_snap_clone.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='loadgen:snap-clone-btrfs' job=loadgen_btrfs_snap_clone.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfspv-snapshot-clone-btrfs-create $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_loadgen_btrfs_rc_val=$(echo $?)
if [ "$app_loadgen_btrfs_rc_val" != "0" ]; then
app_deprovision_btrfs
fi

}

##############################
# Create zfspv-snapshot-btrfs #
##############################

zfspv_snapshot_btrfs() { 
  
## Generate test name for running litmusbook for creating zfspv snapshot
run_id="btrfs";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=zfspv-snapshot metadata=${run_id})
echo $test_name
cd e2e-tests

# copy the content of run_litmus_test.yml into a different file to update the test specific parameters.
cp experiments/zfs-localpv/functional/zfspv-snapshot/run_litmus_test.yml snap_btrfs.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/generateName: zfspv-snapshot-/generateName: snapshot-zfspv-btrfs/g' \
-e 's/name: zfspv-snapshot-clone/name: snap-clone-btrfs/g' \
-e 's/name: zfspv-snapshot/name: snapshot-btrfs/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: snap-clone-btrfs/}' \
-e '/name: OPERATOR_NAMESPACE/{n;s/.*/            value: openebs/}' \
-e '/name: SNAPSHOT_CLASS/{n;s/.*/            value: zfs-snapshot-class/}' \
-e '/name: SNAPSHOT_NAME/{n;s/.*/            value: snapshot-btrfs/}' \
-e '/name: APP_PVC/{n;s/.*/            value: percona-mysql-claim/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: name=percona/}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/}' snap_btrfs.yml

sed -i '/parameters.yml: |/a \
    dbuser: root\
    dbpassword: k8sDem0\
    dbname: snap_clone_btrfs
' snap_btrfs.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' snap_btrfs.yml

cat snap_btrfs.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='name:snapshot-btrfs' job=snap_btrfs.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfspv-snapshot-clone-btrfs-create $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

zfspv_snapshot_btrfs_rc_val=$(echo $?)
if [ "$zfspv_snapshot_btrfs_rc_val" != "0" ]; then
app_deprovision_btrfs
fi

}

###########################
# create zfspv-clone-btrfs #
###########################

zfspv_clone_btrfs() {

## Generate the test name to run litmusbook for creating zfspv-clone
run_id="btrfs";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=zfspv-clone metadata=${run_id})
echo $test_name
cd e2e-tests

# copy the content of run_litmus_test.yml into a different file to update the test specific parameters.
cp experiments/zfs-localpv/functional/zfspv-clone/run_litmus_test.yml clone_btrfs.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/generateName: zfspv-clone-/generateName: clone-zfspv-btrfs/g' \
-e 's/name: zfspv-clone/name: clone-zfspv-btrfs/g' \
-e 's/name: zfspv-snapshot-clone/name: snap-clone-btrfs/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: snap-clone-btrfs/}' \
-e '/name: OPERATOR_NAMESPACE/{n;s/.*/            value: openebs/}' \
-e '/name: STORAGE_CLASS/{n;s/.*/            value: zfs-sc-btrfs/}' \
-e '/name: SNAPSHOT_NAME/{n;s/.*/            value: snapshot-btrfs/}' \
-e '/name: CLONED_PVC_NAME/{n;s/.*/            value: clone-pvc/}' \
-e '/name: CLONE_PVC_SIZE/{n;s/.*/            value: 5Gi/}' \
-e '/name: APP_NAME/{n;s/.*/            value: percona/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: percona-clone/}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/}' clone_btrfs.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' clone_btrfs.yml

cat clone_btrfs.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='name:clone-zfspv-btrfs' job=clone_btrfs.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfspv-snapshot-clone-btrfs-create $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

zfspv_clone_btrfs_rc_val=$(echo $?)
if [ "$zfspv_clone_btrfs_rc_val" != "0" ]; then
zfspv_snapshot_deprovision_btrfs
app_deprovision_btrfs
fi

}

################################
# Deprovision zfspv-clone-btrfs #
################################

zfspv_clone_btrfs_deprovision() {

## Generate test name to run litmusbook for deprovisioning the zfspv clone
run_id="btrfs-deprovision";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=zfspv-clone metadata=${run_id})
echo $test_name
cd e2e-tests

# copy the content of run_litmus_test.yml into a different file to update the test specific parameters.
cp experiments/zfs-localpv/functional/zfspv-clone/run_litmus_test.yml clone_btrfs_deprovision.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/generateName: zfspv-clone-/generateName: clone-btrfs-deprovision-/g' \
-e '/labels:/{n;s/  name: zfspv-clone/  name: clone-btrfs-deprovision/g}' \
-e 's/name: zfspv-snapshot-clone/name: snap-clone-btrfs/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: snap-clone-btrfs/}' \
-e '/name: OPERATOR_NAMESPACE/{n;s/.*/            value: openebs/}' \
-e '/name: STORAGE_CLASS/{n;s/.*/            value: zfs-sc-btrfs/}' \
-e '/name: SNAPSHOT_NAME/{n;s/.*/            value: snapshot-btrfs/}' \
-e '/name: CLONED_PVC_NAME/{n;s/.*/            value: clone-pvc/}' \
-e '/name: CLONE_PVC_SIZE/{n;s/.*/            value: 5Gi/}' \
-e '/name: APP_NAME/{n;s/.*/            value: percona/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: percona-clone/}' \
-e '/name: ACTION/{n;s/.*/            value: deprovision/}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/}' clone_btrfs_deprovision.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' clone_btrfs_deprovision.yml

cat clone_btrfs_deprovision.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='name:clone-btrfs-deprovision' job=clone_btrfs_deprovision.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfspv-snapshot-clone-btrfs-create $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

zfspv_clone_btrfs_deprovision_rc_val=$(echo $?)
if [ "$zfspv_clone_btrfs_deprovision_rc_val" != "0" ]; then
zfspv_snapshot_deprovision_btrfs
app_deprovision_btrfs
fi

}

###################################
# Deprovision zfspv-snapshot-btrfs #
###################################

zfspv_snapshot_btrfs_deprovision() {

## Generate test name to run litmusbook for deprovisioning the zfspv-snapshot
run_id="btrfs-deprovision";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=zfspv-snapshot metadata=${run_id})
echo $test_name
cd e2e-tests

# copy the content of provisioner run_litmus_test.yml into a different file to update the test specific parameters.
cp experiments/zfs-localpv/functional/zfspv-snapshot/run_litmus_test.yml snap_btrfs_deprovision.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/generateName: zfspv-snapshot-/generateName: snap-btrfs-deprovision-/g' \
-e '/labels:/{n;s/  name: zfspv-snapshot/  name: snap-btrfs-deprovision/g}' \
-e 's/name: zfspv-snapshot-clone/name: snap-clone-btrfs/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: snap-clone-btrfs/}' \
-e '/name: OPERATOR_NAMESPACE/{n;s/.*/            value: openebs/}' \
-e '/name: SNAPSHOT_CLASS/{n;s/.*/            value: zfs-snapshot-class/}' \
-e '/name: SNAPSHOT_NAME/{n;s/.*/            value: snapshot-btrfs/}' \
-e '/name: APP_PVC/{n;s/.*/            value: percona-mysql-claim/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: name=percona/}' \
-e '/name: ACTION/{n;s/.*/            value: deprovision/}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/}' snap_btrfs_deprovision.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' snap_btrfs_deprovision.yml

cat snap_btrfs_deprovision.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='name:snap-btrfs-deprovision' job=snap_btrfs_deprovision.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfspv-snapshot-clone-btrfs-create $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

zfspv_snapshot_btrfs_deprovision_rc_val=$(echo $?)
if [ "$zfspv_snapshot_btrfs_deprovision_rc_val" != "0" ]; then
app_deprovision_btrfs
fi

}

###########################
# Deprovision Application #
###########################

app_deprovision_btrfs() {
  
## Generate test name to run litmusbook for deprovisioning the percona application
run_id="btrfs-snap-clone-deprovision";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=percona-deployment metadata=${run_id})
echo $test_name
cd e2e-tests

# copy the content of run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/percona/deployers/run_litmus_test.yml percona_btrfs_snap_clone_dep.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/app: percona-deployment/app: dep-snap-clone-btrfs/g' \
-e 's/generateName: litmus-percona-/generateName: percona-snap-clone-btrfs-dep-/g' \
-e 's/value: openebs-standard/value: zfs-sc-btrfs/g' \
-e 's/value: provision/value: deprovision/g' \
-e '/name: TARGET_AFFINITY_CHECK/{n;s/value: enable/value: disable/g}' \
-e 's/value: app-percona-ns/value: snap-clone-btrfs/g' percona_btrfs_snap_clone_dep.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' percona_btrfs_snap_clone_dep.yml

cat percona_btrfs_snap_clone_dep.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='app:dep-snap-clone-btrfs' job=percona_btrfs_snap_clone_dep.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfspv-snapshot-clone-btrfs-create $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_deprovision_btrfs_rc_val=$(echo $?)

if [ "$app_deprovision_btrfs_rc_val" -eq "0" ] &&
   [ "$zfspv_snapshot_btrfs_deprovision_rc_val" -eq "0" ] &&
   [ "$zfspv_clone_btrfs_deprovision_rc_val" -eq "0" ] &&
   [ "$zfspv_clone_btrfs_rc_val" -eq "0" ] &&
   [ "$zfspv_snapshot_btrfs_rc_val" -eq "0" ] &&
   [ "$app_loadgen_btrfs_rc_val" -eq "0" ] &&
   [ "$app_deploy_btrfs_rc_val" -eq "0" ]; then

## Update the e2e-result-custom-resources for the job
bash openebs-nativek8s/utils/e2e-cr jobname:zfspv-snapshot-clone-btrfs-create jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Pass
python3 openebs-nativek8s/utils/result/result_update.py $job_id 3F13 3-functional "create volume snapshot and clone when fstype is btrfs" Pass $pipeline_id $current_time $commit_id $gittoken

else
## Update the e2e-result-custom-resources for the job
bash openebs-nativek8s/utils/e2e-cr jobname:zfspv-snapshot-clone-btrfs-create jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Fail
python3 openebs-nativek8s/utils/result/result_update.py $job_id 3F13 3-functional "create volume snapshot and clone when fstype is btrfs" Fail $pipeline_id $current_time $commit_id $gittoken
exit 1;
fi

}


if [ "$1" == "run_job" ];then
  app_deploy_btrfs $2 $3 $4 $5
  app_loadgen_btrfs
  zfspv_snapshot_btrfs
  zfspv_clone_btrfs
  zfspv_clone_btrfs_deprovision
  zfspv_snapshot_btrfs_deprovision
  app_deprovision_btrfs
else
  connect_cluster
fi