#!/bin/bash

## Define and initialize test-result specific variables.
zfspv_shared_mount_ext4_rc_val=1
zfspv_shared_mount_snapshot_ext4_rc_val=1
zfspv_shared_mount_clone_ext4_rc_val=1
zfspv_shared_mount_clone_ext4_deprovision_rc_val=1
zfspv_shared_mount_snapshot_ext4_deprovision_rc_val=1

## SSH into the cluster to run the kubernetes jobs for the experiments
connect_cluster() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port -o LogLevel=ERROR 'cd e2e-nativek8s && bash openebs-nativek8s/pipelines/stages/3-functional/3F15-zfspv-shared-mount-volume-ext4 run_job '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'

}

#######################################################
# Perfom zfspv shared mount test with ext4 file-system #
#######################################################

zfspv_shared_mount_ext4() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

## Pooling over the previous job to wait for its completion
bash openebs-nativek8s/utils/pooling jobname:zfspv-custom-topology
bash openebs-nativek8s/utils/e2e-cr jobname:zfspv-shared-mount-volume-ext4 jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

## Generate the test name for performing the test for zfspv shared mount
run_id="ext4";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=zfspv-shared-mount metadata=${run_id})
echo $test_name
cd e2e-tests

# copy the content of run_litmus_test.yml into a different file to update the test specific parameters.
cp experiments/zfs-localpv/functional/zfspv-shared-mount/run_litmus_test.yml zfspv_shared_mount_ext4.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/name: shared-mount-volume/name: shared-mount-volume-ext4/g' \
-e 's/generateName: zfspv-shared-mount-/generateName: shared-mount-zfspv-ext4-/g' \
-e 's/name: zfspv-shared-mount/name: zfspv-shared-mount-ext4/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: shared-ext4/}' \
-e '/name: APP_PVC/{n;s/.*/            value: shared-pvc-ext4/}' \
-e '/name: STORAGE_CLASS/{n;s/.*/            value: zfs-sc-ext4-shared/}' \
-e '/name: OPERATOR_NAMESPACE/{n;s/.*/            value: openebs/}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: busybox/}' \
-e '/name: ACTION/{n;s/.*/            value: provision/}' zfspv_shared_mount_ext4.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' zfspv_shared_mount_ext4.yml

sed -i '/parameters.yml: |/a \
    blocksize: 4k\
    blockcount: 1024\
    testfile: shared_mount_file
' zfspv_shared_mount_ext4.yml

cat zfspv_shared_mount_ext4.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='name:shared-mount-volume-ext4' job=zfspv_shared_mount_ext4.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfspv-shared-mount-volume-ext4 $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

zfspv_shared_mount_ext4_rc_val=$(echo $?)
if [ "$zfspv_shared_mount_ext4_rc_val" != "0" ]; then
exit 1;
fi

}

###################################
# Volume snapshot for shared zfspv#
###################################

zfspv_shared_mount_snapshot_ext4() {

## Generate test name for running litmusbook for generate load on application
run_id="shared-ext4";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=zfspv-snapshot metadata=${run_id})
echo $test_name
cd e2e-tests

# copy the content of workload run_litmus_test.yml into a different file to update the test specific parameters.
cp experiments/zfs-localpv/functional/zfspv-snapshot/run_litmus_test.yml zfspv_shared_mount_snapshot_ext4.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/generateName: zfspv-snapshot-/generateName: snapshot-zfspv-shared-ext4-/g' \
-e 's/name: zfspv-snapshot-clone/name: snap-clone-shared-ext4/g' \
-e 's/name: zfspv-snapshot/name: snapshot-shared-mount-ext4/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: shared-ext4/}' \
-e '/name: OPERATOR_NAMESPACE/{n;s/.*/            value: openebs/}' \
-e '/name: SNAPSHOT_CLASS/{n;s/.*/            value: zfs-snapshot-class/}' \
-e '/name: SNAPSHOT_NAME/{n;s/.*/            value: shared-mount-snapshot-ext4/}' \
-e '/name: APP_PVC/{n;s/.*/            value: shared-pvc-ext4/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: name=previous-pod/}' zfspv_shared_mount_snapshot_ext4.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' zfspv_shared_mount_snapshot_ext4.yml

cat zfspv_shared_mount_snapshot_ext4.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='name:snapshot-shared-mount-ext4' job=zfspv_shared_mount_snapshot_ext4.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfspv-shared-mount-volume-ext4 $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

zfspv_shared_mount_snapshot_ext4_rc_val=$(echo $?)
if [ "$zfspv_shared_mount_snapshot_ext4_rc_val" != "0" ]; then
zfspv_shared_mount_ext4_deprovision
fi

}

###########################################
#  zfspv-clone for shared-volume snapshot #
###########################################

zfspv_shared_mount_clone_ext4() { 
  
## Generate test name for running litmusbook for creating zfspv snapshot
run_id="shared-ext4";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=zfspv-clone metadata=${run_id})
echo $test_name
cd e2e-tests

# copy the content of run_litmus_test.yml into a different file to update the test specific parameters.
cp experiments/zfs-localpv/functional/zfspv-clone/run_litmus_test.yml zfspv_shared_mount_clone_ext4.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/generateName: zfspv-clone-/generateName: clone-zfspv-shared-ext4/g' \
-e 's/name: zfspv-clone/name: clone-zfspv-shared-ext4/g' \
-e 's/name: zfspv-snapshot-clone/name: snap-clone-shared-ext4/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: shared-ext4/}' \
-e '/name: OPERATOR_NAMESPACE/{n;s/.*/            value: openebs/}' \
-e '/name: STORAGE_CLASS/{n;s/.*/            value: zfs-sc-ext4-shared/}' \
-e '/name: SNAPSHOT_NAME/{n;s/.*/            value: shared-mount-snapshot-ext4/}' \
-e '/name: CLONED_PVC_NAME/{n;s/.*/            value: clone-shared-pvc/}' \
-e '/name: CLONE_PVC_SIZE/{n;s/.*/            value: 4Gi/}' \
-e '/name: APP_NAME/{n;s/.*/            value: busybox/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: busybox-clone/}' zfspv_shared_mount_clone_ext4.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' zfspv_shared_mount_clone_ext4.yml

cat zfspv_shared_mount_clone_ext4.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='name:clone-zfspv-shared-ext4' job=zfspv_shared_mount_clone_ext4.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfspv-shared-mount-volume-ext4 $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

zfspv_shared_mount_clone_ext4_rc_val=$(echo $?)
if [ "$zfspv_shared_mount_clone_ext4_rc_val" != "0" ]; then
zfspv_shared_mount_snapshot_ext4_deprovision
zfspv_shared_mount_ext4_deprovision
fi

}

###########################
# Deprovision zfspv-clone #
###########################

zfspv_shared_mount_clone_ext4_deprovision() {

## Generate test name to run litmusbook for deprovisioning the zfspv clone
run_id="shared-ext4-deprovision";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=zfspv-clone metadata=${run_id})
echo $test_name
cd e2e-tests

# copy the content of run_litmus_test.yml into a different file to update the test specific parameters.
cp experiments/zfs-localpv/functional/zfspv-clone/run_litmus_test.yml zfspv_shared_mount_clone_ext4_deprovision.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/generateName: zfspv-clone-/generateName: zfspv-clone-shared-ext4-deprovision-/g' \
-e '/labels:/{n;s/  name: zfspv-clone/  name: zfspv-clone-shared-ext4-deprovision/g}' \
-e 's/name: zfspv-snapshot-clone/name: snap-clone-shared-ext4/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: shared-ext4/}' \
-e '/name: OPERATOR_NAMESPACE/{n;s/.*/            value: openebs/}' \
-e '/name: STORAGE_CLASS/{n;s/.*/            value: zfs-sc-ext4-shared/}' \
-e '/name: SNAPSHOT_NAME/{n;s/.*/            value: shared-mount-snapshot-ext4/}' \
-e '/name: CLONED_PVC_NAME/{n;s/.*/            value: clone-shared-pvc/}' \
-e '/name: CLONE_PVC_SIZE/{n;s/.*/            value: 4Gi/}' \
-e '/name: APP_NAME/{n;s/.*/            value: busybox/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: busybox-clone/}' \
-e '/name: ACTION/{n;s/.*/            value: deprovision/}' zfspv_shared_mount_clone_ext4_deprovision.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' zfspv_shared_mount_clone_ext4_deprovision.yml

cat zfspv_shared_mount_clone_ext4_deprovision.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='name:zfspv-clone-shared-ext4-deprovision' job=zfspv_shared_mount_clone_ext4_deprovision.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfspv-shared-mount-volume-ext4 $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

zfspv_shared_mount_clone_ext4_deprovision_rc_val=$(echo $?)
if [ "$zfspv_shared_mount_clone_ext4_deprovision_rc_val" != "0" ]; then
zfspv_shared_mount_snapshot_ext4_deprovision
zfspv_shared_mount_ext4_deprovision
fi

}

###########################
# Deprovision zfspv-snapshot #
###########################

zfspv_shared_mount_snapshot_ext4_deprovision() {

## Generate test name to run litmusbook for deprovisioning the zfspv-snapshot
run_id="shared-ext4-deprovision";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=zfspv-snapshot metadata=${run_id})
echo $test_name
cd e2e-tests

# copy the content of provisioner run_litmus_test.yml into a different file to update the test specific parameters.
cp experiments/zfs-localpv/functional/zfspv-snapshot/run_litmus_test.yml zfspv_shared_mount_snapshot_ext4_deprovision.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/generateName: zfspv-snapshot-/generateName: zfspv-snapshot-shared-ext4-deprovision-/g' \
-e '/labels:/{n;s/  name: zfspv-snapshot/  name: zfspv-snapshot-shared-ext4-deprovision/g}' \
-e 's/name: zfspv-snapshot-clone/name: snap-clone-shared-ext4/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: shared-ext4/}' \
-e '/name: OPERATOR_NAMESPACE/{n;s/.*/            value: openebs/}' \
-e '/name: SNAPSHOT_CLASS/{n;s/.*/            value: zfs-snapshot-class/}' \
-e '/name: SNAPSHOT_NAME/{n;s/.*/            value: shared-mount-snapshot-ext4/}' \
-e '/name: APP_PVC/{n;s/.*/            value: shared-pvc-ext4/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: name=previous-pod/}' \
-e '/name: ACTION/{n;s/.*/            value: deprovision/}' zfspv_shared_mount_snapshot_ext4_deprovision.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' zfspv_shared_mount_snapshot_ext4_deprovision.yml

cat zfspv_shared_mount_snapshot_ext4_deprovision.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='name:zfspv-snapshot-shared-ext4-deprovision' job=zfspv_shared_mount_snapshot_ext4_deprovision.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfspv-shared-mount-volume-ext4 $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

zfspv_shared_mount_snapshot_ext4_deprovision_rc_val=$(echo $?)
if [ "$zfspv_shared_mount_snapshot_ext4_deprovision_rc_val" != "0" ]; then
zfspv_shared_mount_ext4_deprovision
fi

}


##################################
# Deprovision zfspv-shared-mount #
##################################

zfspv_shared_mount_ext4_deprovision() {

## Generate test name to run litmusbook for deprovisioning the zfspv-snapshot
run_id="ext4-deprovision";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=zfspv-shared-mount metadata=${run_id})
echo $test_name
cd e2e-tests

# copy the content of run_litmus_test.yml into a different file to update the test specific parameters.
cp experiments/zfs-localpv/functional/zfspv-shared-mount/run_litmus_test.yml zfspv_shared_mount_ext4_deprovision.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/name: shared-mount-volume/name: shared-mount-volume-ext4-deprovision/g' \
-e 's/generateName: zfspv-shared-mount-/generateName: shared-mount-zfspv-ext4-deprovision-/g' \
-e 's/name: zfspv-shared-mount/name: zfspv-shared-mount-ext4/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: shared-ext4/}' \
-e '/name: APP_PVC/{n;s/.*/            value: shared-pvc-ext4/}' \
-e '/name: STORAGE_CLASS/{n;s/.*/            value: zfs-sc-ext4-shared/}' \
-e '/name: OPERATOR_NAMESPACE/{n;s/.*/            value: openebs/}' \
-e '/name: ACTION/{n;s/.*/            value: deprovision/}' zfspv_shared_mount_ext4_deprovision.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' zfspv_shared_mount_ext4_deprovision.yml

cat zfspv_shared_mount_ext4_deprovision.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='name:shared-mount-volume-ext4-deprovision' job=zfspv_shared_mount_ext4_deprovision.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfspv-shared-mount-volume-ext4 $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

zfspv_shared_mount_ext4_deprovision_rc_val=$(echo $?)

if [ "$zfspv_shared_mount_ext4_deprovision_rc_val" -eq "0" ] &&
   [ "$zfspv_shared_mount_snapshot_ext4_deprovision_rc_val" -eq "0" ] &&
   [ "$zfspv_shared_mount_clone_ext4_deprovision_rc_val" -eq "0" ] &&
   [ "$zfspv_shared_mount_clone_ext4_rc_val" -eq "0" ] &&
   [ "$zfspv_shared_mount_snapshot_ext4_rc_val" -eq "0" ] &&
   [ "$zfspv_shared_mount_ext4_rc_val" -eq "0" ]; then

## Update the e2e-result-custom-resources for the job
bash openebs-nativek8s/utils/e2e-cr jobname:zfspv-shared-mount-volume-ext4 jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Pass
python3 e2e-nativek8s/openebs-nativek8s/utils/result/result_update.py $job_id 3F15 3-functional "zfspv shared mount volume support when fstype is ext4" Pass $pipeline_id $current_time $commit_id $gittoken

else
## Update the e2e-result-custom-resources for the job
bash openebs-nativek8s/utils/e2e-cr jobname:zfspv-shared-mount-volume-ext4 jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Fail
python3 e2e-nativek8s/openebs-nativek8s/utils/result/result_update.py $job_id 3F15 3-functional "zfspv shared mount volume support when fstype is ext4" Fail $pipeline_id $current_time $commit_id $gittoken
exit 1;
fi

}


if [ "$1" == "run_job" ];then
  zfspv_shared_mount_ext4 $2 $3 $4 $5
  zfspv_shared_mount_snapshot_ext4
  zfspv_shared_mount_clone_ext4
  zfspv_shared_mount_clone_ext4_deprovision
  zfspv_shared_mount_snapshot_ext4_deprovision
  zfspv_shared_mount_ext4_deprovision

else
  connect_cluster
fi