#!/bin/bash

## Define and initialize test-result specific variables.
app_deploy_rc_val=1
app_loadgen_rc_val=1
zfs_backup_same_ns_rc_val=1
zfs_restore_same_ns_rc_val=1
restore_app_deprovision_rc_val=1

## SSH into the cluster to run the kubernetes jobs for the experiments
connect_cluster() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $zfs_user@$zfs_ip -p $zfs_port -o LogLevel=ERROR 'cd e2e-nativek8s && bash openebs-nativek8s/pipelines/stages/3-functional/3F21-zfs-backup-restore-same-ns run_job '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$VELERO_PLUGIN_NAME'"' '"'$VELERO_VERSION'"'

}

#######################################
# Deploy percona application on ZFSPV #
#######################################

app_deploy() {
diff
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
velero_plugin=$(echo $4)
velero_version=$(echo $5)
source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

## Pooling over the previous job to wait for its completion
bash openebs-nativek8s/utils/zfs-e2e-cr jobname:zfs-backup-restore-same-ns jobphase:Waiting
bash openebs-nativek8s/utils/zfs-e2e-cr jobname:ext4-backup-restore-same-ns jobphase:Waiting
bash openebs-nativek8s/utils/zfs-e2e-cr jobname:xfs-backup-restore-same-ns jobphase:Waiting
bash openebs-nativek8s/utils/zfs-e2e-cr jobname:zfs-backup-restore-same-ns jobphase:Waiting
bash openebs-nativek8s/utils/zfs-e2e-cr jobname:ext4-backup-restore-same-ns jobphase:Waiting
bash openebs-nativek8s/utils/zfs-e2e-cr jobname:xfs-backup-restore-same-ns jobphase:Waiting
bash openebs-nativek8s/utils/zfs-e2e-cr jobname:zfs-backup-restore-same-node jobphase:Waiting
bash openebs-nativek8s/utils/zfs-e2e-cr jobname:ext4-backup-restore-same-node jobphase:Waiting
bash openebs-nativek8s/utils/zfs-e2e-cr jobname:xfs-backup-restore-same-node jobphase:Waiting
bash openebs-nativek8s/utils/zfs-e2e-cr jobname:zfs-incr-backup-restore jobphase:Waiting
bash openebs-nativek8s/utils/zfs-e2e-cr jobname:zfs-backup-restore-same-ns jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

## Generate the test name for running the litmusbook for percona deployment
test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=percona-provision-zfs-bkp-same-ns metadata='')
echo $test_name

## copy the content of provisioner run_e2e_test.yml into a temporary file to update the test specific parameters.
cd zfs-localpv/e2e-tests
cp apps/percona/deployers/run_e2e_test.yml percona_zfs_bkp_same_ns.yml

# Modify test specific values in runner file using sed command
sed -i -e "/name: APP_NAMESPACE/{n;s/value: 'percona'/value: 'zfs-bkp-same-ns'/g}" \
-e 's/generateName: percona-deploy-/generateName: percona-zfs-bkp-restore-same-ns-/g' \
-e 's/app: percona-deployment/app: percona-zfs-bkp-same-ns/g' percona_zfs_bkp_same_ns.yml

cat percona_zfs_bkp_same_ns.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../../openebs-nativek8s/utils/e2e_job_runner label='app:percona-zfs-bkp-same-ns' job=percona_zfs_bkp_same_ns.yml
## Get the cluster state Once the litmus jobs completed.
bash ../../openebs-nativek8s/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfs-backup-restore-same-ns $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_deploy_rc_val=$(echo $?)
if [ "$app_deploy_rc_val" != "0" ]; then
exit 1;
fi

}

################
#  App_Loaden  #
################

app_loadgen() {

## Generate test name for running litmusbook for generate load on application
test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=percona-loadgen-zfs-bkp-same-ns metadata='')
echo $test_name
cd zfs-localpv/e2e-tests

# copy the content of workload run_e2e_test.yml into a sameerent file to update the test specific parameters.
cp apps/percona/workload/run_e2e_test.yml loadgen_zfs_bkp_restore_same_ns.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/loadgen: percona-loadjob/loadgen: percona-loadjob-zfs-bkp-same-ns/g' \
-e 's/generateName: percona-loadgen-/generateName: percona-loadgen-zfs-bkp-same-ns-/g' \
-e "/name: APP_NAMESPACE/{n;s/value: 'percona'/value: 'zfs-bkp-same-ns'/g}" loadgen_zfs_bkp_restore_same_ns.yml

cat loadgen_zfs_bkp_restore_same_ns.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../../openebs-nativek8s/utils/e2e_job_runner label='loadgen:percona-loadjob-zfs-bkp-restore-same-ns' job=loadgen_zfs_bkp_restore_same_ns.yml
## Get the cluster state Once the litmus jobs completed.
bash ../../openebs-nativek8s/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfs-backup-restore-same-ns $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_loadgen_rc_val=$(echo $?)
if [ "$app_loadgen_rc_val" != "0" ]; then
exit 1;
fi

}

#########################
#  zfspv-velero-backup  #
#########################

zfs_backup_same_ns() {

## Generate the test name for running the litmusbook for percona deployment
run_id="zfs-bkp-same-ns";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=zfspv-velero-backup-restore metadata=${run_id})
echo $test_name

## copy the content of run_e2e_test.yml into a temporary file to update the test specific parameters.
cd zfs-localpv/e2e-tests
cp experiments/functional/backup_and_restore/run_e2e_test.yml zfs_backup_same_ns.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/generateName: zfspv-velero-backup-restore-/generateName: zfs-backup-same-ns-/g' \
-e 's/test: velero-backup-restore/test: zfs-bkp-same-ns/g' \
-e 's/name: zfspv-backup-store/name: configmap-zfs-backup-restore-same-ns/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: zfs-bkp-same-ns/g}' \
-e '/name: APP_LABEL/{n;s/.*/            value: app=percona/g}' \
-e '/name: APP_PVC/{n;s/.*/            value: percona-pvc/g}' \
-e '/name: ACTION/{n;s/.*/            value: backup/g}' \
-e '/name: VELERO_BACKUP_NAME/{n;s/.*/            value: zfs-same-ns-backup/g}' \
-e "/name: VELERO_PLUGIN_NAME/{n;s/.*/            value: ${velero_plugin}/g}" \
-e "/name: VELERO_VERSION/{n;s/.*/            value: ${velero_version}/g}" \
-e '/name: STORAGE_BUCKET/{n;s/.*/            value: minio/g}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/g}' zfs_backup_same_ns.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' zfs_backup_same_ns.yml

sed -i '/parameters.yml: |/a \
    dbuser: root\
    dbpassword: k8sDem0\
    dbname: zfs_bkp_same_ns
' zfs_backup_same_ns.yml

cat zfs_backup_same_ns.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../../openebs-nativek8s/utils/e2e_job_runner label='test:zfs-bkp-same-ns' job=zfs_backup_same_ns.yml
## Get the cluster state Once the litmus jobs completed.
bash ../../openebs-nativek8s/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfs-backup-restore-same-ns $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

zfs_backup_same_ns_rc_val=$(echo $?)
if [ "$zfs_backup_same_ns_rc_val" != "0" ]; then
exit 1;
fi

}

############################
#   zfspv-velero-restore   #
############################

zfs_restore_same_ns() {

## Generate the test name for running the litmusbook for percona deployment
run_id="zfs-restore-same-ns";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=zfspv-velero-backup-restore metadata=${run_id})
echo $test_name

## copy the content of run_e2e_test.yml into a temporary file to update the test specific parameters.
cd zfs-localpv/e2e-tests
cp experiments/functional/backup_and_restore/run_e2e_test.yml zfs_restore_same_ns.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/generateName: zfspv-velero-backup-restore-/generateName: zfs-restore-same-ns-/g' \
-e 's/test: velero-backup-restore/test: zfs-restore-same-ns/g' \
-e 's/name: zfspv-backup-store/name: configmap-zfs-backup-restore-same-ns/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: zfs-bkp-same-ns/g}' \
-e '/name: APP_LABEL/{n;s/.*/            value: app=percona/g}' \
-e '/name: APP_PVC/{n;s/.*/            value: percona-pvc/g}' \
-e '/name: ACTION/{n;s/.*/            value: restore/g}' \
-e '/name: VELERO_BACKUP_NAME/{n;s/.*/            value: zfs-same-ns-backup/g}' \
-e "/name: VELERO_PLUGIN_NAME/{n;s/.*/            value: ${velero_plugin}/g}" \
-e "/name: VELERO_VERSION/{n;s/.*/            value: ${velero_version}/g}" \
-e '/name: STORAGE_BUCKET/{n;s/.*/            value: minio/g}' \
-e '/name: RESTORE_IN_DIFF_NAMESPACE/{n;s/.*/            value: "false"/g}' \
-e '/name: RESTORE_NAMESPACE/{n;s/.*/            value: zfs-restore-same-ns/g}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/g}' zfs_restore_same_ns.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' zfs_restore_same_ns.yml

sed -i '/parameters.yml: |/a \
    dbuser: root\
    dbpassword: k8sDem0\
    dbname: zfs_bkp_same_ns
' zfs_restore_same_ns.yml

cat zfs_backup_same_ns.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../../openebs-nativek8s/utils/e2e_job_runner label='test:zfs-restore-same-ns' job=zfs_restore_same_ns.yml
## Get the cluster state Once the litmus jobs completed.
bash ../../openebs-nativek8s/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfs-backup-restore-same-ns $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

zfs_restore_same_ns_rc_val=$(echo $?)

if [ "$zfs_restore_same_ns_rc_val" != "0" ]; then
exit 1 ;
fi

}

#######################################
#   Deprovision restore application   #
#######################################

restore_app_deprovision() {

## Generate the test name for running the litmusbook for percona deployment deprovision
run_id="restore";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=percona-deprovision-zfs-bkp-same-ns metadata='')
echo $test_name

## copy the content of provisioner run_e2e_test.yml into a temporary file to update the test specific parameters.
cd zfs-localpv/e2e-tests
cp apps/percona/deployers/run_e2e_test.yml percona_dep_zfs_restore_same_ns.yml

# Modify test specific values in runner file using sed command
sed -i -e "/name: APP_NAMESPACE/{n;s/value: 'percona'/value: 'zfs-restore-same-ns'/g}" \
-e 's/app: percona-deployment/app: percona-deprovision-zfs-restore-same-ns/g' \
-e 's/generateName: percona-deploy-/generateName: percona-deprovision-zfs-restore-same-ns-/g' \
-e "s/value: 'provision'/value: 'deprovision'/g" percona_dep_zfs_restore_same_ns.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' percona_dep_zfs_restore_same_ns.yml

cat percona_dep_zfs_restore_same_ns.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../../openebs-nativek8s/utils/e2e_job_runner label='app:percona-deprovision-zfs-restore-same-ns' job=percona_dep_zfs_restore_same_ns.yml
## Get the cluster state Once the litmus jobs completed.
bash ../../openebs-nativek8s/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfs-backup-restore-same-ns $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

restore_app_deprovision_rc_val=$(echo $?)

if [ "$restore_app_deprovision_rc_val" != "0" ]; then
exit 1;
fi

}

#######################################
#   Deprovision percona application   #
#######################################

app_deprovision() {

## Generate the test name for running the litmusbook for percona deployment deprovision
test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=percona-provision-zfs-bkp-same-ns metadata='')
echo $test_name

## copy the content of provisioner run_e2e_test.yml into a temporary file to update the test specific parameters.
cd zfs-localpv/e2e-tests
cp apps/percona/deployers/run_e2e_test.yml percona_dep_zfs_bkp_same_ns.yml

# Modify test specific values in runner file using sed command
sed -i -e "/name: APP_NAMESPACE/{n;s/value: 'percona'/value: 'zfs-bkp-same-ns'/g}" \
-e 's/app: percona-deployment/app: percona-deprovision-zfs-bkp-same-ns/g' \
-e 's/generateName: percona-deploy-/generateName: percona-deprovision-zfs-bkp-same-ns-/g' \
-e "s/value: 'provision'/value: 'deprovision'/g" percona_dep_zfs_bkp_same_ns.yml

cat percona_dep_zfs_bkp_same_ns.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../../openebs-nativek8s/utils/e2e_job_runner label='app:percona-deprovision-zfs-bkp-same-ns' job=percona_dep_zfs_bkp_same_ns.yml
## Get the cluster state Once the litmus jobs completed.
bash ../../openebs-nativek8s/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfs-backup-restore-same-ns $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_deprovision_rc_val=$(echo $?)

if [ "$app_deprovision_rc_val" -eq "0" ] &&
   [ "$restore_app_deprovision_rc_val" -eq "0" ] &&
   [ "$zfs_restore_same_ns_rc_val" -eq "0" ] &&
   [ "$zfs_backup_same_ns_rc_val" -eq "0" ] &&
   [ "$app_loadgen_rc_val" -eq "0" ] &&
   [ "$app_deploy_rc_val" -eq "0" ]; then

## Update the e2e-result-custom-resources for the job
bash openebs-nativek8s/utils/zfs-e2e-cr jobname:zfs-backup-restore-same-ns jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Pass
#python3 openebs-nativek8s/utils/result/result_update.py $job_id 3F21 3-functional "create backup of zfs volume and restore in sameerent namespace" Pass $pipeline_id "$current_time" $commit_id $gittoken

else
## Update the e2e-result-custom-resources for the job
bash openebs-nativek8s/utils/zfs-e2e-cr jobname:zfs-backup-restore-same-ns jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Fail
#python3 openebs-nativek8s/utils/result/result_update.py $job_id 3F21 3-functional "create backup of zfs volume and restore in sameerent namespace" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

}


if [ "$1" == "run_job" ];then
  app_deploy $2 $3 $4 $5 $6
  app_loadgen
  zfs_backup_same_ns
  zfs_restore_same_ns
  restore_app_deprovision
  app_deprovision
else
  connect_cluster
fi
