#!/bin/bash

## Define and initialize test-result specific variables.
app_deploy_rc_val=1
app_loadgen_rc_val=1
clone_from_pvc_xfs_rc_val=1

## SSH into the cluster to run the kubernetes jobs for the experiments
connect_cluster() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port -o LogLevel=ERROR 'cd e2e-nativek8s && bash openebs-nativek8s/pipelines/stages/3-functional/3F26-zfspv-clone-from-pvc-xfs run_job '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'

}

#######################################
# Deploy percona application on ZFSPV #
#######################################

app_deploy() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

## Pooling over the previous job to wait for its completion
bash openebs-nativek8s/utils/e2e-cr jobname:zfspv-clone-from-pvc-xfs jobphase:Waiting
bash openebs-nativek8s/utils/e2e-cr jobname:zfspv-clone-from-pvc-xfs jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

## Generate the test name for running the litmusbook for percona deployment
run_id="clone-from-pvc-xfs";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=percona-deployment metadata=${run_id})
echo $test_name

## copy the content of provisioner run_litmus_test.yml into a temporary file to update the test specific parameters.
cd e2e-tests
cp apps/percona/deployers/run_litmus_test.yml percona_clone_from_pvc_xfs.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/app: percona-deployment/app: percona-clone-from-pvc-xfs/g' \
-e 's/generateName: litmus-percona-/generateName: litmus-percona-clone-from-pvc-xfs-/g' \
-e 's/value: openebs-standard/value: zfs-sc-xfs/g' \
-e '/name: TARGET_AFFINITY_CHECK/{n;s/value: enable/value: disable/g}' \
-e 's/value: app-percona-ns/value: pvc-clone-xfs/g' percona_clone_from_pvc_xfs.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' percona_clone_from_pvc_xfs.yml

cat percona_clone_from_pvc_xfs.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='app:percona-clone-from-pvc-xfs' job=percona_clone_from_pvc_xfs.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfspv-clone-from-pvc-xfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_deploy_rc_val=$(echo $?)
if [ "$app_deploy_rc_val" != "0" ]; then
exit 1;
fi

}

################
#  App_Loaden  #
################

app_loadgen() {

## Generate test name for running litmusbook for generate load on application
run_id="clone-from-pvc-xfs";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=percona-loadgen metadata=${run_id})
echo $test_name
cd e2e-tests

# copy the content of workload run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/percona/workload/run_litmus_test.yml loadgen_clone_from_pvc_xfs.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/loadgen: percona-loadjob/loadgen: loadgen-clone-from-pvc-xfs/g' \
-e 's/generateName: percona-loadgen-/generateName: percona-loadgen-clone-from-pvc-xfs-/g' \
-e 's/value: app-percona-ns/value: pvc-clone-xfs/g' loadgen_clone_from_pvc_xfs.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' loadgen_clone_from_pvc_xfs.yml

cat loadgen_clone_from_pvc_xfs.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='loadgen:loadgen-clone-from-pvc-xfs' job=loadgen_clone_from_pvc_xfs.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfspv-clone-from-pvc-xfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_loadgen_rc_val=$(echo $?)
if [ "$app_loadgen_rc_val" != "0" ]; then
app_deprovision
fi

}

#############################################################
#  Create clone directly from pvc when file-system is xfs   #
#############################################################

clone_from_pvc_xfs() {

## Generate the test name for running the litmusbook for percona deployment
run_id="xfs";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=zfspv-clone-from-pvc metadata=${run_id})
echo $test_name

## copy the content of run_litmus_test.yml into a temporary file to update the test specific parameters.
cd e2e-tests
cp experiments/zfs-localpv/functional/zfspv-clone-directly-from-pvc/run_litmus_test.yml clone_from_pvc_xfs.yml

# Modify test specific values in runner file using sed command
sed -i -e '/name: APP_NAMESPACE/{n;s/.*/            value: pvc-clone-xfs/g}' \
-e '/name: PARENT_PVC_NAME{n;s/.*/            value: percona-mysql-claim/g}' \
-e '/name: OPERATOR_NAMESPACE/{n;s/.*/            value: openebs/g}' \
-e '/name: STORAGE_CLASS/{n;s/.*/            value: zfs-sc-xfs/g}' \
-e '/name: CLONED_PVC_NAME/{n;s/.*/            value: clone-pvc-xfs/g}' \
-e '/name: CLONE_PVC_SIZE/{n;s/.*/            value: 5Gi/g}' \
-e '/name: APP_NAME/{n;s/.*/            value: percona/g}' \
-e '/name: APP_LABEL/{n;s/.*/            value: xfs-pvc-clone/g}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/g}' \
-e 's/generateName: zfspv-clone-from-pvc/generateName: clone-from-pvc-xfs-/g' \
-e 's/name: zfspv-clone-from-pvc/name: clone-from-pvc-xfs/g' clone_from_pvc_xfs.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' clone_from_pvc_xfs.yml


sed -i '/parameters.yml: |/a \
    dbuser: root\
    dbpassword: k8sDem0\
    dbname: pvc_clone_xfs
' clone_from_pvc_xfs.yml

cat clone_from_pvc_xfs.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='name:clone-from-pvc-xfs' job=clone_from_pvc_xfs.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfspv-clone-from-pvc-xfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

clone_from_pvc_xfs_rc_val=$(echo $?)
if [ "$clone_from_pvc_xfs_rc_val" != "0" ]; then
app_deprovision
fi

}


#######################################
#   Deprovision percona application   #
#######################################

app_deprovision() {

## Generate the test name for running the litmusbook for percona deployment
run_id="dep-clone-from-pvc-xfs";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=percona-deployment metadata=${run_id})
echo $test_name

## copy the content of provisioner run_litmus_test.yml into a temporary file to update the test specific parameters.
cd e2e-tests
cp apps/percona/deployers/run_litmus_test.yml percona_dep_clone_from_pvc_xfs.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/app: percona-deployment/app: percona-clone-from-pvc-xfs/g' \
-e 's/generateName: litmus-percona-/generateName: litmus-percona-clone-from-pvc-xfs-/g' \
-e 's/value: openebs-standard/value: zfs-sc-xfs/g' \
-e '/name: TARGET_AFFINITY_CHECK/{n;s/value: enable/value: disable/g}' \
-e 's/value: provision/value: deprovision/g' \
-e 's/value: app-percona-ns/value: pvc-clone-xfs/g' percona_dep_clone_from_pvc_xfs.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' percona_dep_clone_from_pvc_xfs.yml

cat percona_dep_clone_from_pvc_xfs.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='app:percona-clone-from-pvc-xfs' job=percona_dep_clone_from_pvc_xfs.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfspv-clone-from-pvc-xfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_deprovision_rc_val=$(echo $?)

if [ "$app_deprovision_rc_val" -eq "0" ] &&
   [ "$clone_from_pvc_xfs_rc_val" -eq "0" ] &&
   [ "$app_loadgen_rc_val" -eq "0" ] &&
   [ "$app_deploy_rc_val" -eq "0" ]; then

## Update the e2e-result-custom-resources for the job
bash openebs-nativek8s/utils/e2e-cr jobname:zfspv-clone-from-pvc-xfs jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Pass
python3 openebs-nativek8s/utils/result/result_update.py $job_id 3F26 3-functional "Creation of clone directly from pvc when fstype is zfs" Pass $pipeline_id "$current_time" $commit_id $gittoken

else
## Update the e2e-result-custom-resources for the job
bash openebs-nativek8s/utils/e2e-cr jobname:zfspv-clone-from-pvc-xfs jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Fail
python3 openebs-nativek8s/utils/result/result_update.py $job_id 3F26 3-functional "Creation of clone directly from pvc when fstype is xfs" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

}

if [ "$1" == "run_job" ];then
  app_deploy $2 $3 $4
  app_loadgen
  clone_from_pvc_xfs
  app_deprovision
else
  connect_cluster
fi