#!/bin/bash

## Define and initialize test-result specific variables.
app_deploy_rc_val=1
app_loadgen_rc_val=1
app_pod_kill_zfs_rc_val=1

## SSH into the cluster to run the kubernetes jobs for the experiments
connect_cluster() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port -o LogLevel=ERROR 'cd e2e-nativek8s && bash openebs-nativek8s/pipelines/stages/4-chaos/4C01-app-pod-kill-zfs run_job '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'

}

#######################################
# Deploy percona application on ZFSPV #
#######################################

app_deploy() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

## Pooling over the previous job to wait for its completion
bash openebs-nativek8s/utils/e2e-cr jobname:app-pod-kill-zfs jobphase:Waiting
bash openebs-nativek8s/utils/e2e-cr jobname:app-pod-kill-zfs jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

## Generate the test name for running the litmusbook for percona deployment
run_id="app-kill-zfs";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=percona-deployment metadata=${run_id})
echo $test_name

## copy the content of provisioner run_litmus_test.yml into a temporary file to update the test specific parameters.
cd e2e-tests
cp apps/percona/deployers/run_litmus_test.yml percona_deploy_app_kill_zfs.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/app: percona-deployment/app: percona-deploy-app-kill-zfs/g' \
-e 's/generateName: litmus-percona-/generateName: percona-deploy-app-kill-zfs-/g' \
-e 's/value: openebs-standard/value: zfs-sc-zfs/g' \
-e '/name: TARGET_AFFINITY_CHECK/{n;s/value: enable/value: disable/g}' \
-e 's/value: app-percona-ns/value: app-kill-zfs/g' percona_deploy_app_kill_zfs.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' percona_deploy_app_kill_zfs.yml

cat percona_deploy_app_kill_zfs.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='app:percona-deploy-app-kill-zfs' job=percona_deploy_app_kill_zfs.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:app-pod-kill-zfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_deploy_rc_val=$(echo $?)
if [ "$app_deploy_rc_val" != "0" ]; then
exit 1;
fi

}

######################
#    App loadgen     #
######################

app_loadgen() {

## Generate test name for running litmusbook for generate load on application
run_id="app-kill-zfs";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=percona-loadgen metadata=${run_id})
echo $test_name
cd e2e-tests

# copy the content of workload run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/percona/workload/run_litmus_test.yml loadgen_app_kill_zfs.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/loadgen: percona-loadjob/loadgen: percona-loadjob-app-kill-zfs/g' \
-e 's/generateName: percona-loadgen-/generateName: percona-loadgen-app-kill-zfs-/g' \
-e 's/value: app-percona-ns/value: app-kill-zfs/g' loadgen_app_kill_zfs.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' loadgen_app_kill_zfs.yml

cat loadgen_app_kill_zfs.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='loadgen:percona-loadjob-app-kill-zfs' job=loadgen_app_kill_zfs.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:app-pod-kill-zfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_loadgen_rc_val=$(echo $?)
if [ "$app_loadgen_rc_val" != "0" ]; then
app_deprovision
fi

}

####################
#   App pod kill   #
####################

app_pod_kill_zfs() {

run_id="zfs";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=application-pod-failure metadata=${run_id})
echo $test_name

cd e2e-tests
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp experiments/chaos/app_pod_failure/run_litmus_test.yml appkill_zfs.yml

sed -i -e 's/app=jenkins-app/name=percona/g' \
-e 's/generateName: application-pod-failure-/generateName: application-pod-failure-zfs/g' \
-e 's/name: application-pod-failure/name: application-pod-failure-zfs/g' \
-e 's/name: app-failure/name: app-kill-zfs-configmap/g' \
-e 's/value: app-jenkins-ns/value: app-kill-zfs/g' appkill_zfs.yml

## Replace the value of DATA_PERSISTENCE with application name in litmus experiment. 
sed -i '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/}' appkill_zfs.yml

## Insert the set of variables for busybox data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    dbuser: root\
    dbpassword: k8sDem0\
    dbname: appkillzfs
' appkill_zfs.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' appkill_zfs.yml

cat appkill_zfs.yml

bash ../openebs-nativek8s/utils/litmus_job_runner label='name:application-pod-failure-zfs' job=appkill_zfs.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash openebs-nativek8s/utils/dump_cluster_state;
bash openebs-nativek8s/utils/event_updater jobname:app-pod-kill-zfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_pod_kill_zfs_rc_val=$(echo $?)
if [ "$app_pod_kill_zfs_rc_val" != "0" ]; then
app_deprovision
fi

}

#######################################
#   Deprovision percona application   #
#######################################

app_deprovision() {

## Generate test name for running litmusbook for generate load on application
run_id="deprovision-app-kill-zfs";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=percona-deployment metadata=${run_id})
echo $test_name

# copy the content of workload run_litmus_test.yml into a temporary file to update the test specific parameters.
cd e2e-tests
cp apps/percona/deployers/run_litmus_test.yml percona_deprovision_app_kill_zfs.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/app: percona-deployment/app: percona-deprovision-app-kill-zfs/g' \
-e 's/generateName: litmus-percona-/generateName: percona-deprovision-app-kill-zfs-/g' \
-e 's/value: openebs-standard/value: zfs-sc-zfs/g' \
-e '/name: TARGET_AFFINITY_CHECK/{n;s/value: enable/value: disable/g}' \
-e 's/value: app-percona-ns/value: app-kill-zfs/g' percona_deploy_app_kill_zfs.yml
-e 's/value: provision/value: deprovision/g' percona_deprovision_app_kill_zfs.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' percona_deprovision_app_kill_zfs.yml           

cat percona_deprovision_app_kill_zfs.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='app:percona-deprovision-app-kill-zfs' job=percona_deprovision_app_kill_zfs.yml
cd ..
## Get the cluster state Once the litmus jobs completed.
bash openebs-nativek8s/utils/dump_cluster_state;
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:app-pod-kill-zfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_deprovision_rc_val=$(echo $?)

if [ "$app_deprovision_rc_val" -eq "0" ] &&
   [ "$app_pod_kill_zfs_rc_val" -eq "0" ] &&
   [ "$app_loadgen_rc_val" -eq "0" ] &&
   [ "$app_deploy_rc_val" -eq "0" ]; then

## Update the e2e-result-custom-resources for the job
bash openebs-nativek8s/utils/e2e-cr jobname:app-pod-kill-zfs jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Pass
python3 openebs-nativek8s/utils/result/result_update.py $job_id 4C01 4-chaos "Kill the application pod container when fstype is zfs" Pass $pipeline_id "$current_time" $commit_id $gittoken

else
## Update the e2e-result-custom-resources for the job
bash openebs-nativek8s/utils/e2e-cr jobname:app-pod-kill-zfs jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Fail
python3 openebs-nativek8s/utils/result/result_update.py $job_id 4C01 4-chaos "Kill the application pod container when fstype is zfs" Fail $pipeline_id "$current_time" $commit_id $gittoken

exit 1;
fi

}

if [ "$1" == "run_job" ];then
  app_deploy $2 $3 $4
  app_loadgen
  app_pod_kill_zfs
  app_deprovision
else
  connect_cluster
fi
