#!/bin/bash
set -x
pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-nativek8s && bash openebs-nativek8s/pipelines/stages/3-functional/ZFS-volume-provision-percona/ZFS-volume-provision-percona node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'

}

node() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

echo "*******ZFS volume provision**************"

bash openebs-nativek8s/utils/pooling jobname:s3-j1-zfs-pv-provisioner
bash openebs-nativek8s/utils/e2e-cr jobname:s3-j2-zfs-volume-provision-percona jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"


## Deploying Percona Application on ZFS volume

run_id="zfs-pv";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=percona-deployment metadata=${run_id})
echo $test_name
cd litmus

# copy the content of provisioner run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/percona/deployers/run_litmus_test.yml deploy_percona_zfspv.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/app: percona-deployment/app: deploy-percona-zfs-pv/g' \
-e 's/generateName: litmus-percona-/generateName: litmus-percona-zfspv-/g' \
-e 's/value: openebs-standard/value: zfs-sc/g' \
-e '/name: TARGET_AFFINITY_CHECK/{n;s/value: enable/value: disable/g}' \
-e 's/value: app-percona-ns/value: percona-zfspv/g' deploy_percona_zfspv.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' deploy_percona_zfspv.yml


cat deploy_percona_zfspv.yml

bash ../openebs-nativek8s/utils/litmus_job_runner label='app:deploy-percona-zfs-pv' job=deploy_percona_zfspv.yml
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
bash openebs-nativek8s/utils/event_updater jobname:s3-j2-zfs-volume-provision-percona $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
exit 1;
fi


################
# LitmusBook 2 #
################

run_id="deprovision";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=percona-deployment metadata=${run_id})
echo $test_name

cd litmus
cp apps/percona/deployers/run_litmus_test.yml deprovision_percona_zfspv.yml

sed -i -e 's/app: percona-deployment/app: deprovision-percona-zfs-pv/g' \
-e 's/generateName: litmus-percona-/generateName: litmus-percona-zfspv-dep-/g' \
-e 's/value: openebs-standard/value: zfs-sc/g' \
-e 's/value: provision/value: deprovision/g' \
-e '/name: TARGET_AFFINITY_CHECK/{n;s/value: enable/value: disable/g}' \
-e 's/value: app-percona-ns/value: percona-zfspv/g' deprovision_percona_zfspv.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' deprovision_percona_zfspv.yml           

echo "Running the litmus test for percona Deprovision.."
cat deprovision_percona_zfspv.yml

bash ../openebs-nativek8s/utils/litmus_job_runner label='app:deprovision-percona-zfs-pv' job=deprovision_percona_zfspv.yml
cd ..
bash openebs-nativek8s/utils/dump_cluster_state;
bash openebs-nativek8s/utils/event_updater jobname:s3-j2-zfs-volume-provision-percona $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

#################
## GET RESULT  ##
#################

rc_val=$(echo $?)

source ~/.profile
gittoken=$(echo "$github_token")
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash openebs-nativek8s/utils/e2e-cr jobname:s3-j2-zfs-volume-provision-percona jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:$testResult

#python3 openebs-nativek8s/utils/result/result_update.py $job_id 3-functional "Deploy percona application on zfs volume with zfs file system" $testResult $pipeline_id "$current_time" $commit_id $gittoken
if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi

