## Define the stages & order of execution

stages:
    - CLUSTER-SETUP
    - PROVISIONER
    - FUNCTIONAL-1
    - FUNCTIONAL-2
    - CHAOS
    - INFRA-CHAOS
    - CLEANUP

##################################

1S01-KUBEADM-CLUSTER:
  image: openebs/openshift-ci:latest
  stage: CLUSTER-SETUP 
  tags: 
    - k8s-native
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/1-cluster-setup/1S01-cluster-setup
    - ./openebs-nativek8s/pipelines/stages/1-cluster-setup/1S01-cluster-setup

##################################

.provisioner_test_template:
  image: openebs/openshift-ci:latest
  stage: PROVISIONER
  tags:
    - k8s-native
  when: always
  dependencies:
    - 1S01-KUBEADM-CLUSTER

2P01-ZFS-LOCALPV-PROVISIONER-DEPLOY:
  extends: .provisioner_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/2-provisioner/2P01-zfs-localpv-provisioner
    - ./openebs-nativek8s/pipelines/stages/2-provisioner/2P01-zfs-localpv-provisioner

2P02-ZFS-LOCALPV-CONTROLLER-HA:
  extends: .provisioner_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/2-provisioner/2P02-zfs-controller-high-availability
    - ./openebs-nativek8s/pipelines/stages/2-provisioner/2P02-zfs-controller-high-availability
    
##################################

.func1_test_template:
  image: openebs/openshift-ci:latest
  stage: FUNCTIONAL-1
  tags:
    - k8s-native
  when: always
  dependencies:
    - 2P01-ZFS-LOCALPV-PROVISIONER-DEPLOY

3F01-ZFSPV-CUSTOM-TOPOLOGY-VERIFY:
  extends: .func1_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F01-zfspv-custom-topology-verify
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F01-zfspv-custom-topology-verify

3F02-ZFSPV-RAW-BLOCK-VOLUME:
  extends: .func1_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F02-zfspv-raw-block-volume
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F02-zfspv-raw-block-volume
    
3F03-ZFS-VOLUME-RESIZE-ZFS:
  extends: .func1_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F03-zfs-volume-resize-zfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F03-zfs-volume-resize-zfs

3F04-ZFS-VOLUME-RESIZE-EXT4:
  extends: .func1_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F04-zfs-volume-resize-ext4
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F04-zfs-volume-resize-ext4

3F05-ZFS-VOLUME-RESIZE-XFS:
  extends: .func1_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F05-zfs-volume-resize-xfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F05-zfs-volume-resize-xfs

3F06-ZFSPV-PROPERTY-MODIFY-ZFS:
  extends: .func1_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F06-zfspv-property-modify-zfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F06-zfspv-property-modify-zfs
      
3F07-ZFSPV-PROPERTY-MODIFY-EXT4:
  extends: .func1_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F07-zfspv-property-modify-ext4
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F07-zfspv-property-modify-ext4

3F08-ZFSPV-PROPERTY-MODIFY-XFS:
  extends: .func1_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F08-zfspv-property-modify-xfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F08-zfspv-property-modify-xfs

3F09-ZV-PROPERTY-MODIFY-BTRFS:
  extends: .func1_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F09-zfspv-property-modify-btrfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F09-zfspv-property-modify-btrfs

3F10-ZFSPV-SNAPSHOT-CLONE-ZFS-CREATE:
  extends: .func1_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F10-zfspv-snapshot-clone-zfs-create
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F10-zfspv-snapshot-clone-zfs-create

3F11-ZFSPV-SNAPSHOT-CLONE-EXT4-CREATE:
  extends: .func1_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F11-zfspv-snapshot-clone-ext4-create
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F11-zfspv-snapshot-clone-ext4-create

3F12-ZFSPV-SNAPSHOT-CLONE-XFS-CREATE:
  extends: .func1_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F12-zfspv-snapshot-clone-xfs-create
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F12-zfspv-snapshot-clone-xfs-create

3F13-ZFSPV-SNAPSHOT-CLONE-BTRFS-CREATE:
  extends: .func1_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F13-zfspv-snapshot-clone-btrfs-create
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F13-zfspv-snapshot-clone-btrfs-create

3F14-ZFSPV-SHARED-MOUNT-VOLUME-ZFS:
  extends: .func1_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F14-zfspv-shared-mount-volume-zfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F14-zfspv-shared-mount-volume-zfs

3F15-ZFSPV-SHARED-MOUNT-VOLUME-EXT4:
  extends: .func1_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F15-zfspv-shared-mount-volume-ext4
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F15-zfspv-shared-mount-volume-ext4

3F16-ZFSPV-SHARED-MOUNT-VOLUME-XFS:
  extends: .func1_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F16-zfspv-shared-mount-volume-xfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F16-zfspv-shared-mount-volume-xfs

3F17-ZFSPV-SHARED-MOUNT-VOLUME-BTRFS:
  extends: .func1_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F17-zfspv-shared-mount-volume-btrfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F17-zfspv-shared-mount-volume-btrfs

##################################

.func2_test_template:
  image: openebs/openshift-ci:latest
  stage: FUNCTIONAL-2
  tags:
    - k8s-native
  when: always
  dependencies:
    - 2P01-ZFS-LOCALPV-PROVISIONER-DEPLOY

3F18-ZFS-BACKUP-RESTORE-DIFF-NS:
  extends: .func2_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F18-zfs-backup-restore-diff-ns
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F18-zfs-backup-restore-diff-ns

3F19-EXT4-BACKUP-RESTORE-DIFF-NS:
  extends: .func2_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F19-ext4-backup-restore-diff-ns
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F19-ext4-backup-restore-diff-ns

3F20-XFS-BACKUP-RESTORE-DIFF-NS:
  extends: .func2_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F20-xfs-backup-restore-diff-ns
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F20-xfs-backup-restore-diff-ns

3F21-ZFS-BACKUP-RESTORE-SAME-NS:
  extends: .func2_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F21-zfs-backup-restore-same-ns
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F21-zfs-backup-restore-same-ns

3F22-EXT4-BACKUP-RESTORE-SAME-NS:
  extends: .func2_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F22-ext4-backup-restore-same-ns
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F22-ext4-backup-restore-same-ns

3F23-XFS-BACKUP-RESTORE-SAME-NS:
  extends: .func2_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F23-xfs-backup-restore-same-ns
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F23-xfs-backup-restore-same-ns

3F24-ZFSPV-CLONE-FROM-PVC-ZFS:
  extends: .func2_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F24-zfspv-clone-from-pvc-zfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F24-zfspv-clone-from-pvc-zfs

3F25-ZFSPV-CLONE-FROM-PVC-EXT4:
  extends: .func2_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F25-zfspv-clone-from-pvc-ext4
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F25-zfspv-clone-from-pvc-ext4

3F26-ZFSPV-CLONE-FROM-PVC-XFS:
  extends: .func2_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F26-zfspv-clone-from-pvc-xfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F26-zfspv-clone-from-pvc-xfs
       
3F27-ZFS-BACKUP-RESTORE-DIFF-NODE:
  extends: .func2_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F27-zfs-backup-restore-diff-node
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F27-zfs-backup-restore-diff-node

3F28-EXT4-BACKUP-RESTORE-DIFF-NODE:
  extends: .func2_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F28-ext4-backup-restore-diff-node
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F28-ext4-backup-restore-diff-node

3F29-XFS-BACKUP-RESTORE-DIFF-NODE:
  extends: .func2_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F29-xfs-backup-restore-diff-node
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F29-xfs-backup-restore-diff-node

3F30-ZFS-INCREMENTAL-BACKUP-RESTORE:
  extends: .func2_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F30-xfs-incremental-backup-restore
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F30-xfs-incremental-backup-restore

3F31-EXT4-INCREMENTAL-BACKUP-RESTORE:
  extends: .func2_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F31-ext4-incremental-backup-restore
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F31-ext4-incremental-backup-restore

3F32-XFS-INCREMENTAL-BACKUP-RESTORE:
  extends: .func2_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F32-xfs-incremental-backup-restore
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F32-xfs-incremental-backup-restore

##################################

.chaos_template:
  image: openebs/openshift-ci:latest
  stage: CHAOS
  tags:
    - k8s-native
  when: always
  dependencies:
    - 2P01-ZFS-LOCALPV-PROVISIONER-DEPLOY

4C01-APP-POD-KILL-ZFS:
  extends: .chaos_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/4-chaos/4C01-app-pod-kill-zfs
    - ./openebs-nativek8s/pipelines/stages/4-chaos/4C01-app-pod-kill-zfs

4C02-APP-POD-KILL-XFS:
  extends: .chaos_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/4-chaos/4C02-app-pod-kill-xfs
    - ./openebs-nativek8s/pipelines/stages/4-chaos/4C02-app-pod-kill-xfs

4C03-APP-POD-KILL-EXT4:
  extends: .chaos_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/4-chaos/4C03-app-pod-kill-ext4
    - ./openebs-nativek8s/pipelines/stages/4-chaos/4C03-app-pod-kill-ext4
    
4C04-APP-POD-KILL-BTRFS:
  extends: .chaos_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/4-chaos/4C04-app-pod-kill-btrfs
    - ./openebs-nativek8s/pipelines/stages/4-chaos/4C04-app-pod-kill-btrfs

##################################

.infra_chaos_template:
  image: openebs/openshift-ci:latest
  stage: INFRA-CHAOS
  tags:
    - k8s-native
  when: always
  dependencies:
    - 2P01-ZFS-LOCALPV-PROVISIONER-DEPLOY

5I01-NODE-DOCKER-RESTART-ZFS:
  extends: .infra_chaos_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/5-infra-chaos/5I01-node-docker-restart-zfs
    - ./openebs-nativek8s/pipelines/stages/5-infra-chaos/5I01-node-docker-restart-zfs
  
5I02-NODE-KUBELET-RESTART-ZFS:
  extends: .infra_chaos_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/5-infra-chaos/5I02-node-kubelet-restart-zfs
    - ./openebs-nativek8s/pipelines/stages/5-infra-chaos/5I02-node-kubelet-restart-zfs

5I03-NODE-FAILURE-ZFS:
  extends: .infra_chaos_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/5-infra-chaos/5I03-node-failure-zfs
    - ./openebs-nativek8s/pipelines/stages/5-infra-chaos/5I03-node-failure-zfs
    
##################################

6D01-CLUSTER-CLEANUP:
  image: openebs/openshift-ci:latest
  stage: CLEANUP
  when: always
  tags:
    - k8s-native
  dependencies:
    - 2P01-ZFS-LOCALPV-PROVISIONER-DEPLOY
  script:
    - chmod 775 ./openebs-nativek8s/pipelines/stages/6-cleanup/6D01-cluster-cleanup
    - ./openebs-nativek8s/pipelines/stages/6-cleanup/6D01-cluster-cleanup
