## Define the stages & order of execution

stages:
    - CLUSTER-SETUP
    - PROVIDER-INFRA-SETUP
    - FUNCTIONAL-TEST
    - INFRA-CHAOS
    - OPENEBS-CLEANUP
    - CLUSTER-CLEANUP

##################################

KUBEADM-CLUSTER:
  image: openebs/openshift-ci:latest
  stage: CLUSTER-SETUP 
  tags: 
    - k8s-native
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/1-cluster-setup/cluster-setup
    - ./openebs-nativek8s/pipelines/stages/1-cluster-setup/cluster-setup

##################################

# OPENEBS-DEPLOY:
#   image: openebs/openshift-ci:latest
#   stage: PROVIDER-INFRA-SETUP
#   tags:
#     - k8s-native
#   dependencies:
#     - KUBEADM-CLUSTER
#   script: 
#     - chmod 755 ./openebs-nativek8s/pipelines/stages/2-Infra-setup/deploy-openebs/deploy-openebs
#     - ./openebs-nativek8s/pipelines/stages/2-Infra-setup/deploy-openebs/deploy-openebs

# OPENEBS-SC-DEPLOY:
#   image: openebs/openshift-ci:latest
#   stage: PROVIDER-INFRA-SETUP
#   tags:
#     - k8s-native
#   dependencies:
#     - KUBEADM-CLUSTER
#   script:
#     - chmod 755 ./openebs-nativek8s/pipelines/stages/2-Infra-setup/storage-policies/openebs-sc
#     - ./openebs-nativek8s/pipelines/stages/2-Infra-setup/storage-policies/openebs-sc

# SPC-STRIPED-POOL:
#   image: openebs/openshift-ci:latest
#   stage: PROVIDER-INFRA-SETUP
#   tags:
#     - k8s-native
#   dependencies:
#     - KUBEADM-CLUSTER
#   script:
#     - chmod 755 ./openebs-nativek8s/pipelines/stages/2-Infra-setup/create-striped-pool/create-striped-pool
#     - ./openebs-nativek8s/pipelines/stages/2-Infra-setup/create-striped-pool/create-striped-pool

##################################

.func_test_template:
  image: openebs/openshift-ci:latest
  stage: FUNCTIONAL-TEST
  tags:
    - k8s-native
  when: always
  dependencies:
    - KUBEADM-CLUSTER

ZFS-LOCALPV-PROVISIONER-DEPLOY:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/ZFS-LocalPV-provisioner/ZFS-LocalPV-provisioner
    - ./openebs-nativek8s/pipelines/stages/3-functional/ZFS-LocalPV-provisioner/ZFS-LocalPV-provisioner

ZFS-LOCALPV-CONTROLLER-HA:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/ZFS-controller-in-HA/ZFS-controller-in-HA
    - ./openebs-nativek8s/pipelines/stages/3-functional/ZFS-controller-in-HA/ZFS-controller-in-HA

ZFSPV-RAW-BLOCK-VOLUME:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-raw-block-volume/ZFSPV-raw-block-volume
    - ./openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-raw-block-volume/ZFSPV-raw-block-volume
    
ZFSPV-CUSTOM-TOPOLOGY-VERIFY:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-custom-topology/ZFSPV-custom-topology
    - ./openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-custom-topology/ZFSPV-custom-topology
      
ZFSPV-SNAPSHOT-CLONE-ZFS-CREATE:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-snapshot-clone/ZFSPV-snapshot-clone
    - ./openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-snapshot-clone/ZFSPV-snapshot-clone

ZFSPV-SNAPSHOT-CLONE-EXT4-CREATE:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-snapshot-clone-ext4/ZFSPV-snapshot-clone-ext4
    - ./openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-snapshot-clone-ext4/ZFSPV-snapshot-clone-ext4

ZFSPV-SNAPSHOT-CLONE-XFS-CREATE:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-snapshot-clone-xfs/ZFSPV-snapshot-clone-xfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-snapshot-clone-xfs/ZFSPV-snapshot-clone-xfs

ZFSPV-SNAPSHOT-CLONE-BTRFS-CREATE:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-snapshot-clone-btrfs/ZFSPV-snapshot-clone-btrfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-snapshot-clone-btrfs/ZFSPV-snapshot-clone-btrfs

ZFS-VOL-RESIZE-ZFS:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/ZFS-vol-resize/ZFS-vol-resize
    - ./openebs-nativek8s/pipelines/stages/3-functional/ZFS-vol-resize/ZFS-vol-resize

ZFS-VOL-RESIZE-EXT4:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/ZFS-vol-resize-ext4/ZFS-vol-resize-ext4
    - ./openebs-nativek8s/pipelines/stages/3-functional/ZFS-vol-resize-ext4/ZFS-vol-resize-ext4

ZFS-VOL-RESIZE-XFS:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/ZFS-vol-resize-xfs/ZFS-vol-resize-xfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/ZFS-vol-resize-xfs/ZFS-vol-resize-xfs

ZFSPV-PROPERTY-MODIFY-ZFS:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/ZV-property-modify/ZV-property-modify
    - ./openebs-nativek8s/pipelines/stages/3-functional/ZV-property-modify/ZV-property-modify

ZFSPV-PROPERTY-MODIFY-EXT4:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/ZV-property-modify-ext4/ZV-property-modify-ext4
    - ./openebs-nativek8s/pipelines/stages/3-functional/ZV-property-modify-ext4/ZV-property-modify-ext4

ZFSPV-PROPERTY-MODIFY-XFS:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/ZV-property-modify-xfs/ZV-property-modify-xfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/ZV-property-modify-xfs/ZV-property-modify-xfs
  
ZV-PROPERTY-MODIFY-BTRFS:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/ZV-property-modify-btrfs/ZV-property-modify-btrfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/ZV-property-modify-btrfs/ZV-property-modify-btrfs

ZFSPV-SHARED-MOUNT-VOLUME-ZFS:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/zfspv-shared-mount-zfs/zfspv-shared-mount-zfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/zfspv-shared-mount-zfs/zfspv-shared-mount-zfs

ZFSPV-SHARED-MOUNT-VOLUME-EXT4:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/zfspv-shared-mount-ext4/zfspv-shared-mount-ext4
    - ./openebs-nativek8s/pipelines/stages/3-functional/zfspv-shared-mount-ext4/zfspv-shared-mount-ext4

ZFSPV-SHARED-MOUNT-VOLUME-XFS:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/zfspv-shared-mount-xfs/zfspv-shared-mount-xfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/zfspv-shared-mount-xfs/zfspv-shared-mount-xfs

##################################

# .cleanup_test_template:
#   image: openebs/openshift-ci:latest
#   stage:  OPENEBS-CLEANUP
#   tags:
#     - k8s-native
#   when: always
#   dependencies:
#       - OPENEBS-DEPLOY
      
# CLEANUP-SPC-STRIPED-POOL:
#   extends: .cleanup_test_template
#   script:
#     - chmod 755 ./openebs-nativek8s/pipelines/stages/4-cleanup/cleanup-spc-striped-pool/cleanup-spc-striped-pool
#     - ./openebs-nativek8s/pipelines/stages/4-cleanup/cleanup-spc-striped-pool/cleanup-spc-striped-pool

# OPENEBS-UNINSTALL:
#   extends: .cleanup_test_template
#   script:
#     - chmod 755 ./openebs-nativek8s/pipelines/stages/4-cleanup/openebs-uninstall/openebs-uninstall
#     - ./openebs-nativek8s/pipelines/stages/4-cleanup/openebs-uninstall/openebs-uninstall

##################################

.infra_chaos_template:
  image: openebs/openshift-ci:latest
  stage: INFRA-CHAOS
  tags:
    - k8s-native
  when: always
  dependencies:
    - KUBEADM-CLUSTER

ZFS-DOCKER-RESTART:
  extends: .infra_chaos_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/4-infra-chaos/docker-restart/docker-restart
    - ./openebs-nativek8s/pipelines/stages/4-infra-chaos/docker-restart/docker-restart
  
ZFS-KUBELET-RESTART:
  extends: .infra_chaos_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/4-infra-chaos/kubelet-restart/kubelet-restart
    - ./openebs-nativek8s/pipelines/stages/4-infra-chaos/kubelet-restart/kubelet-restart

##################################

CLUSTER-DELETE:
  image: openebs/openshift-ci:latest
  stage: CLUSTER-CLEANUP
  when: always
  tags:
    - k8s-native
  dependencies:
    - KUBEADM-CLUSTER
  script:
    - chmod 775 ./openebs-nativek8s/pipelines/stages/5-cleanup/cluster-cleanup/cluster-cleanup
    - ./openebs-nativek8s/pipelines/stages/5-cleanup/cluster-cleanup/cluster-cleanup
