## Define the stages & order of execution

stages:
    - CLUSTER-SETUP
    - PROVISIONER
    - FUNCTIONAL-1
    # - FUNCTIONAL-2
    - CHAOS
    - INFRA-CHAOS
    - CLEANUP

##################################

1S01-KUBEADM-CLUSTER:
  image: openebs/openshift-ci:latest
  stage: CLUSTER-SETUP 
  tags: 
    - k8s-native
  script:
    - chmod 755 ./pipeline/stages/1-cluster-setup/1S01-cluster-setup
    - ./pipeline/stages/1-cluster-setup/1S01-cluster-setup

##################################

.provisioner_test_template:
  image: openebs/openshift-ci:latest
  stage: PROVISIONER
  tags:
    - k8s-native
  when: always
  dependencies:
    - 1S01-KUBEADM-CLUSTER

2P01-LVM-LOCALPV-PROVISIONER-DEPLOY:
  extends: .provisioner_test_template
  script:
    - chmod 755 ./pipeline/stages/2-provisioner/2P01-lvm-localpv-provisioner
    - ./pipeline/stages/2-provisioner/2P01-lvm-localpv-provisioner

2P02-LVM-LOCALPV-CONTROLLER-HA:
  extends: .provisioner_test_template
  script:
    - chmod 755 ./pipeline/stages/2-provisioner/2P02-lvm-controller-high-availability
    - ./pipeline/stages/2-provisioner/2P02-lvm-controller-high-availability
    
##################################

.func1_test_template:
  image: openebs/openshift-ci:latest
  stage: FUNCTIONAL-1
  tags:
    - k8s-native
  when: always
  dependencies:
    - 2P01-LVM-LOCALPV-PROVISIONER-DEPLOY

3F01-LVM-VOLUME-RESIZE-EXT4:
  extends: .func1_test_template
  script:
    - chmod 755 ./pipeline/stages/3-functional/3F01-lvm-volume-resize
    - ./pipeline/stages/3-functional/3F01-lvm-volume-resize

3F02-LVMPV-VOLUME-RESIZE-XFS:
  extends: .func1_test_template
  script:
    - chmod 755 ./pipeline/stages/3-functional/3F02-lvm-volume-resize-xfs
    - ./pipeline/stages/3-functional/3F02-lvm-volume-resize-xfs

3F03-LVMPV-VOLUME-RESIZE-BTRFS:
  extends: .func1_test_template
  script:
    - chmod 755 ./pipeline/stages/3-functional/3F03-lvm-volume-resize-btrfs
    - ./pipeline/stages/3-functional/3F03-lvm-volume-resize-btrfs

3F04-LVMPV-CUSTOM-TOPOLOGY:
  extends: .func1_test_template
  script:
    - chmod 755 ./pipeline/stages/3-functional/3F04-lvmpv-custom-topology
    - ./pipeline/stages/3-functional/3F04-lvmpv-custom-topology

3F05-LVMPV-SHARED-MOUNT-EXT4:
  extends: .func1_test_template
  script:
    - chmod 755 ./pipeline/stages/3-functional/3F05-lvmpv-shared-mount-volume-ext4
    - ./pipeline/stages/3-functional/3F05-lvmpv-shared-mount-volume-ext4

3F06-LVMPV-SHARED-MOUNT-XFS:
  extends: .func1_test_template
  script:
    - chmod 755 ./pipeline/stages/3-functional/3F06-lvmpv-shared-mount-volume-xfs
    - ./pipeline/stages/3-functional/3F06-lvmpv-shared-mount-volume-xfs

3F07-LVMPV-SHARED-MOUNT-BTRFS:
  extends: .func1_test_template
  script:
    - chmod 755 ./pipeline/stages/3-functional/3F07-lvmpv-shared-mount-volume-btrfs
    - ./pipeline/stages/3-functional/3F07-lvmpv-shared-mount-volume-btrfs

3F08-LVMPV-SNAPSHOT-EXT4:
  extends: .func1_test_template
  script:
    - chmod 755 ./pipeline/stages/3-functional/3F08-lvmpv-snapshot-ext4
    - ./pipeline/stages/3-functional/3F08-lvmpv-snapshot-ext4

3F09-LVMPV-SNAPSHOT-XFS:
  extends: .func1_test_template
  script:
    - chmod 755 ./pipeline/stages/3-functional/3F09-lvmpv-snapshot-xfs
    - ./pipeline/stages/3-functional/3F09-lvmpv-snapshot-xfs

3F10-LVMPV-SNAPSHOT-BTRFS:
  extends: .func1_test_template
  script:
    - chmod 755 ./pipeline/stages/3-functional/3F10-lvmpv-snapshot-btrfs
    - ./pipeline/stages/3-functional/3F10-lvmpv-snapshot-btrfs

##################################

.chaos_template:
  image: openebs/openshift-ci:latest
  stage: CHAOS
  tags:
    - k8s-native
  when: always
  dependencies:
    - 2P01-LVM-LOCALPV-PROVISIONER-DEPLOY

4C01-APP-POD-FAILURE:
  extends: .chaos_template
  script:
    - chmod 755 ./pipeline/stages/4-chaos/4C01-application-pod-failure
    - ./pipeline/stages/4-chaos/4C01-application-pod-failure

##################################

.infra_chaos_template:
  image: openebs/openshift-ci:latest
  stage: INFRA-CHAOS
  tags:
    - k8s-native
  when: always
  dependencies:
    - 2P01-LVM-LOCALPV-PROVISIONER-DEPLOY

5I01-NODE-DOCKER-RESTART:
  extends: .infra_chaos_template
  script:
    - chmod 755 ./pipeline/stages/5-infra-chaos/5I01-node-docker-restart
    - ./pipeline/stages/5-infra-chaos/5I01-node-docker-restart
  
5I02-NODE-KUBELET-RESTART:
  extends: .infra_chaos_template
  script:
    - chmod 755 ./pipeline/stages/5-infra-chaos/5I02-node-kubelet-restart
    - ./pipeline/stages/5-infra-chaos/5I02-node-kubelet-restart

5I03-NODE-POWER-FAILURE:
  extends: .infra_chaos_template
  script:
    - chmod 755 ./pipeline/stages/5-infra-chaos/5I03-node-power-failure
    - ./pipeline/stages/5-infra-chaos/5I03-node-power-failure
    
##################################

6D01-CLUSTER-CLEANUP:
  image: openebs/openshift-ci:latest
  stage: CLEANUP
  when: always
  tags:
    - k8s-native
  dependencies:
    - 2P01-LVM-LOCALPV-PROVISIONER-DEPLOY
  script:
    - chmod 775 ./pipeline/stages/6-cleanup/6D01-cluster-cleanup
    - ./pipeline/stages/6-cleanup/6D01-cluster-cleanup