## Define the stages & order of execution

stages:
    - CLUSTER-SETUP
    - PROVIDER-INFRA-SETUP
    - APP-DEPLOY
    - UPGRADE-LVM-LOCALPV
    - FUNCTIONAL-TEST
    - CLUSTER-CLEANUP

#################################################################################

KUBEADM-CLUSTER:
    image: openebs/openshift-ci:latest
    stage: CLUSTER-SETUP
    tags:
        - k8s-native
    script:
        - chmod 755 ./pipeline/stages/1-cluster-setup/cluster-setup
        - ./pipeline/stages/1-cluster-setup/cluster-setup

#################################################################################

LVM-LOCALPV-PROVISIONER:
    image: openebs/openshift-ci:latest
    stage: PROVIDER-INFRA-SETUP
    dependencies:
        - KUBEADM-CLUSTER
    tags:
        - k8s-native
    script: 
        - chmod 755 ./pipeline/stages/2-provisioner/lvm-localpv-provisioner
        - ./pipeline/stages/2-provisioner/lvm-localpv-provisioner

LVM-CONTROLLER-HA:
    image: openebs/openshift-ci:latest
    stage: PROVIDER-INFRA-SETUP
    dependencies: 
        - KUBEADM-CLUSTER
    tags:
        - k8s-native
    script: 
        - chmod 755 ./pipeline/stages/2-provisioner/lvm-controller-high-availability
        - ./pipeline/stages/2-provisioner/lvm-controller-high-availability

#################################################################################

.app_deploy_template:
    image: openebs/openshift-ci:latest
    stage: APP-DEPLOY
    tags: 
        - k8s-native
    dependencies:
        - LVM-LOCALPV-PROVISIONER

APP-LVM-VOL-RESIZE-BTRFS:
    extends: .app_deploy_template
    script:
        - chmod 755 ./pipeline/stages/3-app-deploy/app-lvm-vol-resize-btrfs
        - ./pipeline/stages/3-app-deploy/app-lvm-vol-resize-btrfs

APP-LVM-VOL-RESIZE-EXT4:
    extends: .app_deploy_template
    script:
        - chmod 755 ./pipeline/stages/3-app-deploy/app-lvm-vol-resize-ext4
        - ./pipeline/stages/3-app-deploy/app-lvm-vol-resize-ext4

APP-LVM-VOL-RESIZE-XFS:
    extends: .app_deploy_template
    script:
        - chmod 755 ./pipeline/stages/3-app-deploy/app-lvm-vol-resize-xfs
        - ./pipeline/stages/3-app-deploy/app-lvm-vol-resize-xfs

#################################################################################

UPGRADE-LVM-LOCALPV:
    image: openebs/openshift-ci:latest
    stage: UPGRADE-LVMLOCALPV
    tags:
        - k8s-native
    dependencies:
        - LVM-LOCALPV-PROVISIONER
    script:
        - chmod 755 ./pipeline/stages/4-upgrade/upgrade-lvm-localpv
        - ./pipeline/stages/4-upgrade/upgrade-lvm-localpv

#################################################################################

.func_test_template:
    image: openebs/openshift-ci:latest
    stage: FUNCTIONAL-TEST
    tags:
        - k8s-native
    dependencies:
        - LVM-LOCALPV-PROVISIONER

LVM-VOL-RESIZE-BTRFS:
    extends: .func_test_template
    script:
        - chmod 755 ./pipeline/stages/5-functional/lvm-vol-resize-btrfs
        - ./pipeline/stages/5-functional/lvm-vol-resize-btrfs

LVM-VOL-RESIZE-EXT4:
    extends: .func_test_template
    script:
        - chmod 755 ./pipeline/stages/5-functional/lvm-vol-resize-ext4
        - ./pipeline/stages/5-functional/lvm-vol-resize-ext4

LVM-VOL-RESIZE-XFS:
    extends: .func_test_template
    script:
        - chmod 755 ./pipeline/stages/5-functional/lvm-vol-resize-xfs
        - ./pipeline/stages/5-functional/lvm-vol-resize-xfs

#################################################################################

CLEANUP-CLUSTER:
    when: always
    image: openebs/openshift-ci:latest
    dependencies:
      - LVM-LocalPV-PROVISIONER
    stage: CLUSTER-CLEANUP
    script:
      - chmod 755 ./pipeline/stages/6-cleanup/cluster-cleanup/cluster-cleanup
      - ./pipeline/stages/6-cleanup/cluster-cleanup/cluster-cleanup