## Define the stages & order of execution

stages:
    - CLUSTER-SETUP
    - PROVIDER-INFRA-SETUP
    - APP-DEPLOY
    - UPGRADE-DEVICE-LOCALPV
    - FUNCTIONAL-TEST
    - CLUSTER-CLEANUP

#################################################################################

KUBEADM-CLUSTER:
    image: openebs/openshift-ci:latest
    stage: CLUSTER-SETUP
    tags:
        - k8s-native
    script:
        - chmod 755 ./pipeline/stages/1-cluster-setup/cluster-setup
        - ./pipeline/stages/1-cluster-setup/cluster-setup

#################################################################################

DEVICE-LOCALPV-PROVISIONER:
    image: openebs/openshift-ci:latest
    stage: PROVIDER-INFRA-SETUP
    dependencies:
        - KUBEADM-CLUSTER
    tags:
        - k8s-native
    script: 
        - chmod 755 ./pipeline/stages/2-provisioner/device-localpv-provisioner
        - ./pipeline/stages/2-provisioner/device-localpv-provisioner

DEVICE-CONTROLLER-HA:
    image: openebs/openshift-ci:latest
    stage: PROVIDER-INFRA-SETUP
    dependencies: 
        - KUBEADM-CLUSTER
    tags:
        - k8s-native
    script: 
        - chmod 755 ./pipeline/stages/2-provisioner/device-controller-high-availability
        - ./pipeline/stages/2-provisioner/device-controller-high-availability

#################################################################################

.app_deploy_template:
    image: openebs/openshift-ci:latest
    stage: APP-DEPLOY
    tags: 
        - k8s-native
    dependencies:
        - DEVICE-LOCALPV-PROVISIONER

APP-DEPLOY-KILL-EXT4:
    extends: .app_deploy_template
    script:
        - chmod 755 ./pipeline/stages/3-app-deploy/app-kill-ext4
        - ./pipeline/stages/3-app-deploy/app-kill-ext4

APP-DEPLOY-KILL-XFS:
    extends: .app_deploy_template
    script:
        - chmod 755 ./pipeline/stages/3-app-deploy/app-kill-xfs
        - ./pipeline/stages/3-app-deploy/app-kill-xfs

#################################################################################

UPGRADE-DEVICE-LOCALPV:
    image: openebs/openshift-ci:latest
    stage: UPGRADE-DEVICE-LOCALPV
    tags:
        - k8s-native
    dependencies:
        - DEVICE-LOCALPV-PROVISIONER
    script:
        - chmod 755 ./pipeline/stages/4-upgrade/upgrade-device-localpv
        - ./pipeline/stages/4-upgrade/upgrade-device-localpv

#################################################################################

.func_test_template:
    image: openebs/openshift-ci:latest
    stage: FUNCTIONAL-TEST
    tags:
        - k8s-native
    dependencies:
        - DEVICE-LOCALPV-PROVISIONER

APP-KILL-EXT4:
    extends: .func_test_template
    script:
        - chmod 755 ./pipeline/stages/5-functional/app-kill-ext4
        - ./pipeline/stages/5-functional/app-kill-ext4

APP-KILL-XFS:
    extends: .func_test_template
    script:
        - chmod 755 ./pipeline/stages/5-functional/app-kill-xfs
        - ./pipeline/stages/5-functional/app-kill-xfs

#################################################################################

CLEANUP-CLUSTER:
    when: always
    image: openebs/openshift-ci:latest
    dependencies:
      - DEVICE-LOCALPV-PROVISIONER
    stage: CLUSTER-CLEANUP
    script:
      - chmod 755 ./pipeline/stages/6-cleanup/cluster-cleanup/cluster-cleanup
      - ./pipeline/stages/6-cleanup/cluster-cleanup/cluster-cleanup
