## Define the stages & order of execution

stages:
    - CLUSTER-SETUP
    - PROVISIONER
    - FUNCTIONAL-1
    # - FUNCTIONAL-2
    - CHAOS
    - INFRA-CHAOS
    - CLEANUP

##################################

1S01-KUBEADM-CLUSTER:
  image: openebs/openshift-ci:latest
  stage: CLUSTER-SETUP 
  tags: 
    - k8s-native
  script:
    - chmod 755 ./pipeline/stages/1-cluster-setup/1S01-cluster-setup
    - ./pipeline/stages/1-cluster-setup/1S01-cluster-setup

##################################

.provisioner_test_template:
  image: openebs/openshift-ci:latest
  stage: PROVISIONER
  tags:
    - k8s-native
  when: always
  dependencies:
    - 1S01-KUBEADM-CLUSTER

2P01-DEVICE-LOCALPV-PROVISIONER-DEPLOY:
  extends: .provisioner_test_template
  script:
    - chmod 755 ./pipeline/stages/2-provisioner/2P01-device-localpv-provisioner
    - ./pipeline/stages/2-provisioner/2P01-device-localpv-provisioner

2P02-DEVICE-LOCALPV-CONTROLLER-HA:
  extends: .provisioner_test_template
  script:
    - chmod 755 ./pipeline/stages/2-provisioner/2P02-device-controller-high-availability
    - ./pipeline/stages/2-provisioner/2P02-device-controller-high-availability
    
##################################

.func1_test_template:
  image: openebs/openshift-ci:latest
  stage: FUNCTIONAL-1
  tags:
    - k8s-native
  when: always
  dependencies:
    - 2P01-DEVICE-LOCALPV-PROVISIONER-DEPLOY

3F01-DEVICEPV-CUSTOM-TOPOLOGY:
  extends: .func1_test_template
  script:
    - chmod 755 ./pipeline/stages/3-functional/3F01-devicepv-custom-topology
    - ./pipeline/stages/3-functional/3F01-devicepv-custom-topology

##################################

.chaos_template:
  image: openebs/openshift-ci:latest
  stage: CHAOS
  tags:
    - k8s-native
  when: always
  dependencies:
    - 2P01-DEVICE-LOCALPV-PROVISIONER-DEPLOY

4C01-APP-KILL-EXT4:
  extends: .chaos_template
  script:
    - chmod 755 ./pipeline/stages/4-chaos/4C01-application-pod-failure-ext4
    - ./pipeline/stages/4-chaos/4C01-application-pod-failure-ext4

4C02-APP-KILL-XFS:
  extends: .chaos_template
  script:
    - chmod 755 ./pipeline/stages/4-chaos/4C01-application-pod-failure-xfs
    - ./pipeline/stages/4-chaos/4C01-application-pod-failure-xfs

##################################

.infra_chaos_template:
  image: openebs/openshift-ci:latest
  stage: INFRA-CHAOS
  tags:
    - k8s-native
  when: always
  dependencies:
    - 2P01-DEVICE-LOCALPV-PROVISIONER-DEPLOY

5I01-NODE-DOCKER-RESTART:
  extends: .infra_chaos_template
  script:
    - chmod 755 ./pipeline/stages/5-infra-chaos/5I01-node-docker-restart
    - ./pipeline/stages/5-infra-chaos/5I01-node-docker-restart
  
5I02-NODE-KUBELET-RESTART:
  extends: .infra_chaos_template
  script:
    - chmod 755 ./pipeline/stages/5-infra-chaos/5I02-node-kubelet-restart
    - ./pipeline/stages/5-infra-chaos/5I02-node-kubelet-restart

5I03-NODE-POWER-FAILURE:
  extends: .infra_chaos_template
  script:
    - chmod 755 ./pipeline/stages/5-infra-chaos/5I03-node-power-failure
    - ./pipeline/stages/5-infra-chaos/5I03-node-power-failure
    
##################################

6D01-CLUSTER-CLEANUP:
  image: openebs/openshift-ci:latest
  stage: CLEANUP
  when: always
  tags:
    - k8s-native
  dependencies:
    - 2P01-DEVICE-LOCALPV-PROVISIONER-DEPLOY
  script:
    - chmod 775 ./pipeline/stages/6-cleanup/6D01-cluster-cleanup
    - ./pipeline/stages/6-cleanup/6D01-cluster-cleanup