## Define the stages & order of execution

stages:
    - CLUSTER-SETUP
    - PROVISIONER
    - FUNCTIONAL
    - INFRA-CHAOS
    - CLEANUP

##################################

1S01-KUBEADM-CLUSTER:
  image: openebs/openshift-ci:latest
  stage: CLUSTER-SETUP 
  tags: 
    - k8s-native
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/1-cluster-setup/1S01-cluster-setup
    - ./openebs-nativek8s/pipelines/stages/1-cluster-setup/1S01-cluster-setup

##################################

.provisioner_test_template:
  image: openebs/openshift-ci:latest
  stage: PROVISIONER
  tags:
    - k8s-native
  when: always
  dependencies:
    - 1S01-KUBEADM-CLUSTER

2P01-ZFS-LOCALPV-PROVISIONER-DEPLOY:
  extends: .provisioner_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/2-provisioner/2P01-zfs-localpv-provisioner
    - ./openebs-nativek8s/pipelines/stages/2-provisioner/2P01-zfs-localpv-provisioner

2P02-ZFS-LOCALPV-CONTROLLER-HA:
  extends: .provisioner_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/2-provisioner/2P02-zfs-controller-high-availability
    - ./openebs-nativek8s/pipelines/stages/2-provisioner/2P02-zfs-controller-high-availability
    
##################################

.func_test_template:
  image: openebs/openshift-ci:latest
  stage: FUNCTIONAL-TEST
  tags:
    - k8s-native
  when: always
  dependencies:
    - 2P01-ZFS-LOCALPV-PROVISIONER-DEPLOY

3F01-ZFSPV-CUSTOM-TOPOLOGY-VERIFY:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F01-zfspv-custom-topology-verify
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F01-zfspv-custom-topology-verify

3F02-ZFSPV-RAW-BLOCK-VOLUME:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F02-zfspv-raw-block-volume
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F02-zfspv-raw-block-volume
    
3F03-ZFS-VOLUME-RESIZE-ZFS:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F03-zfs-volume-resize-zfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F03-zfs-volume-resize-zfs

3F04-ZFS-VOLUME-RESIZE-EXT4:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F04-zfs-volume-resize-ext4
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F04-zfs-volume-resize-ext4

3F05-ZFS-VOLUME-RESIZE-XFS:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F05-zfs-volume-resize-xfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F05-zfs-volume-resize-xfs

3F06-ZFSPV-PROPERTY-MODIFY-ZFS:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F06-zfspv-property-modify-zfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F06-zfspv-property-modify-zfs
      
3F07-ZFSPV-PROPERTY-MODIFY-EXT4:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F07-zfspv-property-modify-ext4
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F07-zfspv-property-modify-ext4

3F08-ZFSPV-PROPERTY-MODIFY-XFS:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F08-zfspv-property-modify-xfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F08-zfspv-property-modify-xfs

3F09-ZV-PROPERTY-MODIFY-BTRFS:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F09-zfspv-property-modify-btrfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F09-zfspv-property-modify-btrfs

3F10-ZFSPV-SNAPSHOT-CLONE-ZFS-CREATE:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F10-zfspv-snapshot-clone-zfs-create
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F10-zfspv-snapshot-clone-zfs-create

3F11-ZFSPV-SNAPSHOT-CLONE-EXT4-CREATE:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F11-zfspv-snapshot-clone-ext4-create
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F11-zfspv-snapshot-clone-ext4-create

3F12-ZFSPV-SNAPSHOT-CLONE-XFS-CREATE:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F12-zfspv-snapshot-clone-xfs-create
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F12-zfspv-snapshot-clone-xfs-create

3F13-ZFSPV-SNAPSHOT-CLONE-BTRFS-CREATE:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F13-zfspv-snapshot-clone-btrfs-create
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F13-zfspv-snapshot-clone-btrfs-create

3F14-ZFSPV-SHARED-MOUNT-VOLUME-ZFS:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F14-zfspv-shared-mount-volume-zfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F14-zfspv-shared-mount-volume-zfs

3F15-ZFSPV-SHARED-MOUNT-VOLUME-EXT4:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F15-zfspv-shared-mount-volume-ext4
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F15-zfspv-shared-mount-volume-ext4

3F16-ZFSPV-SHARED-MOUNT-VOLUME-XFS:
  extends: .func_test_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/3-functional/3F16-zfspv-shared-mount-volume-xfs
    - ./openebs-nativek8s/pipelines/stages/3-functional/3F16-zfspv-shared-mount-volume-xfs

##################################

.infra_chaos_template:
  image: openebs/openshift-ci:latest
  stage: INFRA-CHAOS
  tags:
    - k8s-native
  when: always
  dependencies:
    - 2P01-ZFS-LOCALPV-PROVISIONER-DEPLOY

5I01-NODE-DOCKER-RESTART-ZFS:
  extends: .infra_chaos_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/5-infra-chaos/5I01-node-docker-restart-zfs
    - ./openebs-nativek8s/pipelines/stages/5-infra-chaos/5I01-node-docker-restart-zfs
  
5I02-NODE-KUBELET-RESTART-ZFS:
  extends: .infra_chaos_template
  script:
    - chmod 755 ./openebs-nativek8s/pipelines/stages/5-infra-chaos/5I02-node-kubelet-restart-zfs
    - ./openebs-nativek8s/pipelines/stages/5-infra-chaos/5I02-node-kubelet-restart-zfs

##################################

CLUSTER-CLEANUP:
  image: openebs/openshift-ci:latest
  stage: CLEANUP
  when: always
  tags:
    - k8s-native
  dependencies:
    - 2P01-ZFS-LOCALPV-PROVISIONER-DEPLOY
  script:
    - chmod 775 ./openebs-nativek8s/pipelines/stages/6-cleanup/6D01-cluster-cleanup
    - ./openebs-nativek8s/pipelines/stages/6-cleanup/6D01-cluster-cleanup
