#!/bin/bash

## SSH into the cluster to run the kubernetes jobs for the experiments
connect_cluster() {
mkdir -p /root/.ssh
touch /root/.ssh/id_rsa
echo "$SSH_KEYS" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa
sshpass -p $pass ssh -o StrictHostKeyChecking=no $zfs_user@$zfs_ip -p $zfs_port -i /root/.ssh/id_rsa -o LogLevel=ERROR 'cd e2e-nativek8s && bash pipeline/stages/4-upgrade/upgrade-zfslocalpv run_job '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$TO_VERSION_ZFS_BRANCH'"' '"'$TO_VERSION_ZFS_DRIVER_IMAGE'"' '"'$ZFS_OPERATOR_NAMESPACE'"'

}

#######################################
#    Deploy ZFS LocalPV provisioner   #
#######################################

run_job() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
to_version_zfs_branch=$(echo $4)
to_version_zfs_driver_image=$(echo $5)
zfs_operator_namespace=$(echo $6)
source ~/.profile

time="date"
current_time=$(eval $time)

## Create the e2e-result-custom-resources for the jobs
bash pipeline/utils/zfs-e2e-cr jobname:upgrade-zfslocalpv jobphase:Waiting
bash pipeline/utils/zfs-e2e-cr jobname:upgrade-zfslocalpv jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

## Generate the test name for running the litmusbook for upgrade zfs-localpv
test_name=$(bash pipeline/utils/generate_test_name testcase=upgrade-zfs-localpv metadata="")
echo $test_name

# copy the content of upgrade run_e2e_test.yml into a temporary file to update the test specific parameters.
cd zfs-localpv/e2e-tests
cp experiments/upgrade-zfs-localpv/run_e2e_test.yml upgrade.yml

# Modify test specific values in runner file using sed command
sed -i -e "/name: TO_VERSION_ZFS_BRANCH/{n;s/.*/            value: ${to_version_zfs_branch}/g}" \
-e "/name: TO_VERSION_ZFS_DRIVER_IMAGE/{n;s/.*/            value: ${to_version_zfs_driver_image}/g}" \
-e "/name: ZFS_OPERATOR_NAMESPACE/{n;s/.*/            value: ${zfs_operator_ns}/g}" upgrade.yml

cat upgrade.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='test:zfs-localpv-upgrade' job=upgrade.yml
## Get the cluster state Once the litmus jobs completed.
bash ../../pipeline/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:upgrade-zfs-localpv $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

#################
## GET RESULT  ##
#################

rc_val=$(echo $?)

source ~/.profile
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash pipeline/utils/zfs-e2e-cr jobname:upgrade-zfslocalpv jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:$testResult

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "run_job" ];then
  run_job $2 $3 $4 $5 $6 $7
else
  connect_cluster
fi