#!/bin/bash

## SSH into the cluster to run the kubernetes jobs for the experiments
connect_cluster() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $lvm_user@$ip -p $port -o LogLevel=ERROR 'cd e2e-nativek8s && bash pipeline/stages/4-upgrade/upgrade-lvm-localpv run_job '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$TO_VERSION_LVM_BRANCH'"' '"'$TO_VERSION_LVM_DRIVER_IMAGE'"' '"'$LVM_OPERATOR_NAMESPACE'"'

}

#######################################
#    Deploy lvm LocalPV provisioner   #
#######################################

run_job() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
to_version_lvm_branch=$(echo $4)
to_version_lvm_driver_image=$(echo $5)
lvm_operator_ns=$(echo $6)
source ~/.profile

time="date"
current_time=$(eval $time)

## Create the e2e-result-custom-resources for the jobs
bash pipeline/utils/lvm-e2e-cr jobname:upgrade-lvm-localpv jobphase:Waiting
bash pipeline/utils/lvm-e2e-cr jobname:upgrade-lvm-localpv jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

## Generate the test name for running the e2e-test for upgrade lvm-localpv
test_name=$(bash pipeline/utils/generate_test_name testcase=upgrade-lvm-localpv metadata="")
echo $test_name

# copy the content of upgrade run_e2e_test.yml into a temporary file to update the test specific parameters.
cd lvm-localpv/e2e-tests
cp experiments/upgrade-lvm-localpv/run_e2e_test.yml upgrade.yml

# Modify test specific values in runner file using sed command
sed -i -e "/name: TO_VERSION_LVM_BRANCH/{n;s/.*/            value: ${to_version_lvm_branch}/g}" \
-e "/name: TO_VERSION_LVM_DRIVER_IMAGE/{n;s/.*/            value: ${to_version_lvm_driver_image}/g}" \
-e "/name: LVM_OPERATOR_NAMESPACE/{n;s/.*/            value: ${lvm_operator_ns}/g}" upgrade.yml

cat upgrade.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='test:lvm-localpv-upgrade' job=upgrade.yml
## Get the cluster state Once the litmus jobs completed.
bash ../../pipeline/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:upgrade-lvm-localpv $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

#################
## GET RESULT  ##
#################

rc_val=$(echo $?)

source ~/.profile
testResult=$(kubectl get e2eresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash pipeline/utils/lvm-e2e-cr jobname:upgrade-lvm-localpv jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:$testResult

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "run_job" ];then
  run_job $2 $3 $4 $5 $6 $7
else
  connect_cluster
fi
