#!/bin/bash

## SSH into the cluster to run the kubernetes jobs for the experiments
connect_cluster() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port -o LogLevel=ERROR 'cd e2e-nativek8s && bash openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-custom-topology/ZFSPV-custom-topology run_job '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'

}

#########################################
#  Perform zfspv-custom-topology test   #
#########################################

run_job() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)

source ~/.profile

time="date"
current_time=$(eval $time)

## Create the e2e-result-custom-resources for the jobs

bash openebs-nativek8s/utils/pooling jobname:zfs-ctrl-high-availability
bash openebs-nativek8s/utils/e2e-cr jobname:zfspv-custom-topology jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

## Generate the test name for running the litmusbook for deploying ZFS LocalPV provisioner
test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=zfspv-custom-topology-test metadata="")
echo $test_name

# copy the content of provisioner run_litmus_test.yml into a temporary file to update the test specific parameters.
cd e2e-tests
cp experiment/functional/zfs-LocalPV/zfspv-custom-topology/run_litmus_test.yml run_custom_topology.yml

# Modify test specific values in runner file using sed command
sed -i -e '/name: APP_NAMESPACE/{n;s/.*/            value: topology/g}' \
-e '/name: APP_LABEL/{n;s/.*/            value: test=custom-topology/g}' \
-e '/name: ZPOOL_NAME/{n;s/.*/            value: zfs-test-pool/g}' \
-e '/name: FS_TYPE/{n;s/.*/            value: zfs/g}' \
-e '/name: NODE_LABEL/{n;s/.*/            value: test=custom-topology/g}' run_custom_topology.yml

cat run_custom_topology.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='name:zfspv-custom-topology' job=run_custom_topology.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfspv-custom-topology $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

#################
## GET RESULT  ##
#################

rc_val=$(echo $?)

source ~/.profile
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash openebs-nativek8s/utils/e2e-cr jobname:zfspv-custom-topology jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:$testResult

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "run_job" ];then
  run_job $2 $3 $4
else
  connect_cluster
fi

