#!/bin/bash
pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-nativek8s && bash openebs-nativek8s/pipelines/stages/2-Infra-setup/deploy-openebs/deploy-openebs node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"' '"'$RELEASE_BRANCH'"' '"'$NDM_TAG'"' '"'$E_USER'"' '"'$E_PASSWORD'"'
}

node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
releaseBranch=$(echo $5)
ndmTag=$(echo $6)

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

# for i in efk-vars.yml efk.yml get_url.yml; do
#   wget https://raw.githubusercontent.com/openebs/e2e-infrastructure/master/workload/efk-client/playbook/$i
# done

# echo "EFK: Deploying Aggregrator and Forwarder on client"
# ansible-playbook efk.yml --extra-vars "commit_id=$commit_id pipeline_id=$pipeline_id e_user=$elastic_user e_password=$elastic_password" 

# Applying e2e-CRD
echo "***Applying e2e-crd***********"
kubectl apply -f openebs-nativek8s/utils/e2e-crd.yml

echo "*****Deploying openebs*******"
bash openebs-nativek8s/utils/e2e-cr jobname:s2-j1-deploy-openebs jobphase:Waiting
bash openebs-nativek8s/utils/e2e-cr jobname:s2-j1-deploy-openebs jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"
bash openebs-nativek8s/utils/e2e-cr jobname:s2-j2-cstor-striped-pool jobphase:Waiting 
bash openebs-nativek8s/utils/e2e-cr jobname:s2-j3-policies jobphase:Waiting

source ~/.profile

git clone -b $INFRA_BRANCH https://github.com/openebs/e2e-infrastructure.git
cd e2e-infrastructure/env

######################################################

export OPENEBS_IO_JIVA_CONTROLLER_IMAGE=openebs/jiva:$releaseTag

export OPENEBS_IO_JIVA_REPLICA_IMAGE=openebs/jiva:$releaseTag

export MAYA_APISERVER_IMAGE=openebs/m-apiserver:$releaseTag

export OPENEBS_IO_VOLUME_MONITOR_IMAGE=openebs/m-exporter:$releaseTag

export OPENEBS_IO_CSTOR_VOLUME_MGMT_IMAGE=openebs/cstor-volume-mgmt:$releaseTag

export OPENEBS_IO_CSTOR_POOL_MGMT_IMAGE=openebs/cstor-pool-mgmt:$releaseTag

export OPENEBS_IO_CSTOR_POOL_IMAGE=openebs/cstor-pool:$releaseTag

export OPENEBS_IO_CSTOR_TARGET_IMAGE=openebs/cstor-istgt:$releaseTag

export OPENEBS_IO_CSTOR_POOL_EXPORTER_IMAGE=openebs/m-exporter:$releaseTag

export OPENEBS_LOCALPV_PROVISIONER_IMAGE=$releaseTag

export OPENEBS_ADMISSION_SERVER_IMAGE=$releaseTag

export OPENEBS_SNAPSHOT_OPERATOR_IMAGE=$releaseTag

export OPENEBS_PROVISIONER_IMAGE=$releaseTag

export SNAPSHOT_PROVISIONER_IMAGE=$releaseTag

export CSPC_OPERATOR_IMAGE=$releaseTag

export NODE_DISK_MANAGER_IMAGE=$ndmTag

######################################################

cd ../..

echo "Generating test name***************************"
test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=openebs-provision metadata="")
echo $test_name

## Clone the litmus repo, navigate to litmus root 

git clone https://github.com/mayadata-io/litmus.git
cd litmus

wget https://raw.githubusercontent.com/openebs/e2e-infrastructure/master/env-update/env.py # script to update openebs_setup.yaml
#python3 env.py -f providers/openebs/installers/operator/master/litmusbook/run_litmus_test.yaml

echo "updated yaml"
sed -i -e 's/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g' \
-e "s/value: '10'/value: '20'/g" \
-e "s/value: master/value: $releaseBranch/g" providers/openebs/installers/operator/master/litmusbook/run_litmus_test.yaml

cat providers/openebs/installers/operator/master/litmusbook/run_litmus_test.yaml

#################
## RUNNER MAIN ##
#################

echo "Applying rbac.yml********************************"
kubectl apply -f ./hack/rbac.yaml
kubectl apply -f ./hack/crds.yaml

echo "Copying kube config for litmus"
cp ~/.kube/config admin.conf
kubectl create cm kubeconfig --from-file=admin.conf -n litmus

echo "Running litmus test for openebs deploy.."

run_test=providers/openebs/installers/operator/master/litmusbook/run_litmus_test.yaml
bash ../openebs-nativek8s/utils/litmus_job_runner label='provider:openebs-runner' job=$run_test

echo "Dumping state of cluster post job run"; echo ""
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
bash openebs-nativek8s/utils/event_updater jobname:s2-j1-deploy-openebs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

#################
## GET RESULT  ##
#################

rc_val=$(echo $?)

source ~/.profile

testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash openebs-nativek8s/utils/e2e-cr jobname:s2-j1-deploy-openebs jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:$testResult


if [ "$rc_val" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5 $6 $7 $8 $9
else
  pod
fi