#!/bin/bash
set -x
pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-nativek8s && bash openebs-nativek8s/pipelines/stages/4-cleanup/openebs-uninstall/openebs-uninstall node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

echo "*****Deploying openebs*******"
bash openebs-nativek8s/utils/pooling jobname:s4-j1-cleanup-striped-pool
bash openebs-nativek8s/utils/e2e-cr jobname:s4-j2-openebs-uninstall jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"


echo "Generating test name***************************"
test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=openebs-deprovision metadata="")
echo $test_name


# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp providers/openebs/installers/operator/master/litmusbook/run_litmus_test.yaml cleanup_openebs.yml


sed -i -e 's/name: litmus-openebs-runner/name: litmus-openebs-deprovision/g' \
-e 's/provider: openebs-runner/provider: openebs-deprovision/g' \
-e 's/value: provision/value: deprovision/g' cleanup_openebs.yml

cat cleanup_openebs.yml

bash ../openebs-nativek8s/utils/litmus_job_runner label='provider:openebs-deprovision' job=cleanup_openebs.yml
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
bash openebs-nativek8s/utils/event_updater jobname:s4-j2-openebs-uninstall $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

#################
## GET RESULT  ##
#################

rc_val=$(echo $?)

## Check the test status & result from the litmus result custom resource
source ~/.profile
gittoken=$(echo "$github_token")
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
current_time=$(eval $time)

if [ "$rc_val" != "0" ]; then
bash openebs-nativek8s/utils/e2e-cr jobname:s4-j2-openebs-uninstall jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
#python3 openebs-nativek8s/utils/result/result_update.py $job_id   2-setup "Cleanup OpenEBS related components" $testResult $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

bash openebs-nativek8s/utils/e2e-cr jobname:s4-j2-openebs-uninstall jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass

#python3 openebs-nativek8s/utils/result/result_update.py $job_id   2-setup "Cleanup OpenEBS related components" $testResult $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi