#!/bin/bash

## Define and initialize test-result specific variables.
app_deploy_rc_val=1
csi_vol_resize_rc_val=1
zv_properties_verify_rc_val=1

## SSH into the cluster to run the kubernetes jobs for the experiments
connect_cluster() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $zfs_user@$zfs_ip -p $zfs_port -o LogLevel=ERROR 'cd e2e-nativek8s && bash pipeline/stages/3-functional/3F03-zfs-volume-resize-zfs run_job '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$ZFS_OPERATOR_NAMESPACE'"'

}

#######################################
# Deploy percona application on ZFSPV #
#######################################

app_deploy() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
zfs_operator_namespace=$(echo $4)
source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

## Create the e2e-result-custom-resources for the jobs
bash pipeline/utils/zfs-e2e-cr jobname:zfspv-custom-topology jobphase:Waiting
bash pipeline/utils/zfs-e2e-cr jobname:zfspv-raw-block-volume jobphase:Waiting
bash pipeline/utils/zfs-e2e-cr jobname:zfs-volume-resize-zfs jobphase:Waiting
bash pipeline/utils/zfs-e2e-cr jobname:zfs-volume-resize-ext4 jobphase:Waiting
bash pipeline/utils/zfs-e2e-cr jobname:zfs-volume-resize-xfs jobphase:Waiting
bash pipeline/utils/zfs-e2e-cr jobname:zfspv-property-modify-zfs jobphase:Waiting
bash pipeline/utils/zfs-e2e-cr jobname:zfspv-property-modify-ext4 jobphase:Waiting
bash pipeline/utils/zfs-e2e-cr jobname:zfspv-property-modify-xfs jobphase:Waiting
bash pipeline/utils/zfs-e2e-cr jobname:zfspv-property-modify-btrfs jobphase:Waiting
bash pipeline/utils/zfs-e2e-cr jobname:zfspv-snapshot-clone-zfs-create jobphase:Waiting
bash pipeline/utils/zfs-e2e-cr jobname:zfspv-snapshot-clone-ext4-create jobphase:Waiting
bash pipeline/utils/zfs-e2e-cr jobname:zfspv-snapshot-clone-xfs-create jobphase:Waiting
bash pipeline/utils/zfs-e2e-cr jobname:zfspv-snapshot-clone-btrfs-create jobphase:Waiting
bash pipeline/utils/zfs-e2e-cr jobname:zfspv-shared-mount-volume-zfs jobphase:Waiting
bash pipeline/utils/zfs-e2e-cr jobname:zfspv-shared-mount-volume-ext4 jobphase:Waiting
bash pipeline/utils/zfs-e2e-cr jobname:zfspv-shared-mount-volume-xfs jobphase:Waiting
bash pipeline/utils/zfs-e2e-cr jobname:zfspv-shared-mount-volume-btrfs jobphase:Waiting
bash pipeline/utils/zfs-e2e-cr jobname:zfs-volume-resize-zfs jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

## Generate the test name for running the litmusbook for percona deployment
test_name=$(bash pipeline/utils/generate_test_name testcase=percona-provision-vol-resize-zfs metadata='')
echo $test_name

## copy the content of provisioner run_e2e_test.yml into a temporary file to update the test specific parameters.
cd zfs-localpv/e2e-tests
cp apps/percona/deployers/run_e2e_test.yml deploy_percona_zfspv.yml

# Modify test specific values in runner file using sed command
sed -i -e "/name: APP_NAMESPACE/{n;s/value: 'percona'/value: 'vol-resize-zfs'/g}" \
-e 's/generateName: percona-deploy-/generateName: percona-provision-vol-resize-zfs-/g' \
-e 's/app: percona-deployment/app: percona-deployment-vol-resize-zfs/g' deploy_percona_zfspv.yml

cat deploy_percona_zfspv.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='app:percona-deployment-vol-resize-zfs' job=deploy_percona_zfspv.yml
## Get the cluster state Once the litmus jobs completed.
bash ../../pipeline/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:zfs-volume-resize-zfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_deploy_rc_val=$(echo $?)
if [ "$app_deploy_rc_val" != "0" ]; then
exit 1;
fi

}

#############################
#  ZVOL-properties-verify   #
#############################

zv_properties_verify() {

## Generate the test name for running the litmusbook for percona deployment
run_id="zfs";test_name=$(bash pipeline/utils/generate_test_name testcase=zv-properties-verify metadata=${run_id})
echo $test_name

## copy the content of run_e2e_test.yml into a temporary file to update the test specific parameters.
cd zfs-localpv/e2e-tests
cp experiments/functional/zv-properties-verify/run_e2e_test.yml zv_properties_zfs.yml

# Modify test specific values in runner file using sed command
sed -i -e '/name: APP_NAMESPACE/{n;s/.*/            value: vol-resize-zfs/g}' \
-e '/name: APP_PVC/{n;s/.*/            value: percona-pvc/g}' \
-e "/name: ZFS_OPERATOR_NAMESPACE/{n;s/value: 'openebs'/value: ${zfs_operator_namespace}/g}" \
-e 's/generateName: zv-properties-verify-/generateName: zfs-zv-properties-verify-/g' \
-e 's/test: zv-properties-verify/test: zv-properties-verify-zfs/g' zv_properties_zfs.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' zv_properties_zfs.yml

cat zv_properties_zfs.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='test:zv-properties-verify-zfs' job=zv_properties_zfs.yml
## Get the cluster state Once the litmus jobs completed.
bash ../../pipeline/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:zfs-volume-resize-zfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

zv_properties_verify_rc_val=$(echo $?)
if [ "$zv_properties_verify_rc_val" != "0" ]; then
exit 1;
fi

}

#############################
# CSI volume resize for zfs #
#############################

csi_vol_resize() {

## Generate the test name for running the litmusbook for percona deployment
run_id="zfs";test_name=$(bash pipeline/utils/generate_test_name testcase=csi-volume-resize metadata=${run_id})
echo $test_name

## copy the content of run_e2e_test.yml into a temporary file to update the test specific parameters.
cd zfs-localpv/e2e-tests
cp experiments/functional/csi-volume-resize/run_e2e_test.yml csi_vol_resize_zfs.yml

# Modify test specific values in runner file using sed command
sed -i -e '/name: APP_PVC/{n;s/.*/            value: percona-pvc/g}' \
-e '/name: APP_LABEL/{n;s/.*/            value: app=percona/g}' \
-e 's/test: csi-volume-resize/test: csi-volume-resize-zfs/g' \
-e 's/generateName: csi-volume-resize-/generateName: csi-volume-resize-zfs/g' \
-e '/name: NEW_PV_CAPACITY/{n;s/.*/            value: 10Gi/g}' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: vol-resize-zfs/g}' csi_vol_resize_zfs.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' csi_vol_resize_zfs.yml

cat csi_vol_resize_zfs.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='test:csi-volume-resize-zfs' job=csi_vol_resize_zfs.yml
## Get the cluster state Once the litmus jobs completed.
bash ../../pipeline/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:zfs-volume-resize-zfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

csi_vol_resize_rc_val=$(echo $?)
if [ "$csi_vol_resize_rc_val" != "0" ]; then
exit 1;
fi

}

#######################################
#   Deprovision percona application   #
#######################################

app_deprovision() {

## Generate test name for running litmusbook for generate load on application
test_name=$(bash pipeline/utils/generate_test_name testcase=percona-deprovision-vol-resize-zfs metadata='')
echo $test_name

# copy the content of workload run_e2e_test.yml into a temporary file to update the test specific parameters.
cd zfs-localpv/e2e-tests
cp apps/percona/deployers/run_e2e_test.yml deprovision_percona_zfspv.yml

# Modify test specific values in runner file using sed command
sed -i -e "/name: APP_NAMESPACE/{n;s/value: 'percona'/value: 'vol-resize-zfs'/g}" \
-e 's/app: percona-deployment/app: percona-deprovision-vol-resize-zfs/g' \
-e 's/generateName: percona-deploy-/generateName: percona-deprovision-vol-resize-zfs-/g' \
-e "s/value: 'provision'/value: 'deprovision'/g" deprovision_percona_zfspv.yml  

cat deprovision_percona_zfspv.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='app:percona-deprovision-vol-resize-zfs' job=deprovision_percona_zfspv.yml
cd ../..
## Get the cluster state Once the litmus jobs completed.
bash pipeline/utils/dump_cluster_state;
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:zfs-volume-resize-zfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_deprovision_rc_val=$(echo $?)

if [ "$app_deprovision_rc_val" -eq "0" ] &&
   [ "$zv_properties_verify_rc_val" -eq "0" ] &&
   [ "$csi_vol_resize_rc_val" -eq "0" ] &&
   [ "$app_deploy_rc_val" -eq "0" ]; then

## Update the e2e-result-custom-resources for the job
bash pipeline/utils/zfs-e2e-cr jobname:zfs-volume-resize-zfs jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Pass
#python3 openebs-nativek8s/utils/result/result_update.py $job_id 3F03 3-functional "zv property verify and zfs volume resize when fstype is zfs" Pass $pipeline_id "$current_time" $commit_id $gittoken

else
## Update the e2e-result-custom-resources for the job
bash pipeline/utils/zfs-e2e-cr jobname:zfs-volume-resize-zfs jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Fail
#python3 openebs-nativek8s/utils/result/result_update.py $job_id 3F03 3-functional "zv property verify and zfs volume resize when fstype is zfs" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

}

if [ "$1" == "run_job" ];then
  app_deploy $2 $3 $4 $5
  zv_properties_verify
  csi_vol_resize
  app_deprovision
else
  connect_cluster
fi

