#!/bin/bash

## SSH into the cluster to run the kubernetes jobs for the experiments
connect_cluster() {
mkdir -p /root/.ssh
touch /root/.ssh/id_rsa
echo "$SSH_KEYS" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa
ssh -o StrictHostKeyChecking=no $lvm_user@$ip -p $port -i /root/.ssh/id_rsa -o LogLevel=ERROR 'cd e2e-nativek8s && bash pipeline/stages/3-functional/3F05-lvmpv-shared-mount-volume-ext4 run_job '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'

}

##################################
# Perfom lvmpv shared mount test #
##################################

lvmpv_shared_mount_ext4() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

## Pooling over the previous job to wait for its completion
bash pipeline/utils/pooling jobname:lvmpv-custom-topology
bash pipeline/utils/lvm-e2e-cr jobname:lvmpv-shared-mount-volume-ext4 jobphase:Waiting
bash pipeline/utils/lvm-e2e-cr jobname:lvmpv-shared-mount-volume-ext4 jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

## Generate the test name for performing the test for lvmpv shared mount
run_id="ext4";test_name=$(bash pipeline/utils/generate_test_name testcase=lvmpv-shared-mount-volume metadata=${run_id})

echo $test_name
cd lvm-localpv/e2e-tests

# copy the content of run_e2e_test.yml into a different file to update the test specific parameters.
cp experiments/functional/lvmpv-shared-mount/run_e2e_test.yml lvmpv_shared_mount_ext4.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/name: lvmpv-shared-mount/name: lvmpv-shared-mount-ext4/g' \
-e 's/test: shared-mount/test: shared-mount-ext4/g' \
-e "/name: APP_NAMESPACE/{n;s/value: 'share-ns'/value: 'share-ns-ext4'/g}" lvmpv_shared_mount_ext4.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' lvmpv_shared_mount_ext4.yml

sed -i '/parameters.yml: |/a \
    blocksize: 4k\
    blockcount: 1024\
    testfile: shared_mount_file
' lvmpv_shared_mount_ext4.yml

cat lvmpv_shared_mount_ext4.yml

## Run the Litmus job and get the details of the litmus job from e2e_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='test:shared-mount-ext4' job=lvmpv_shared_mount_ext4.yml
## Get the cluster state Once the litmus jobs completed.
bash ../../pipeline/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:lvmpv-shared-mount-volume-ext4 $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

#################
## GET RESULT  ##
#################

rc_val=$(echo $?)

source ~/.profile
testResult=$(kubectl get e2eresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash pipeline/utils/lvm-e2e-cr jobname:lvmpv-shared-mount-volume-ext4 jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:$testResult

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "run_job" ];then
  lvmpv_shared_mount_ext4 $2 $3 $4
else
  connect_cluster
fi
