#!/bin/bash

connect_cluster() {
mkdir -p /root/.ssh
touch /root/.ssh/id_rsa
echo "$SSH_KEYS" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa
echo $CI_JOB_ID
###clone e2e-nativek8s-repo
echo "cloning e2e-nativek8s repo*************"
ssh -o StrictHostKeyChecking=no -o LogLevel=ERROR $device_user@$device_ip -p $device_port -i /root/.ssh/id_rsa 'git clone -b devicelocalpv-upgrade https://github.com/mayadata-io/e2e-nativek8s.git'
ssh -o StrictHostKeyChecking=no $device_user@$device_ip -p $device_port -i /root/.ssh/id_rsa 'cd e2e-nativek8s && bash pipeline/stages/6-cleanup/cluster-cleanup/cluster-cleanup run_job '"'$CI_JOB_ID'"''
}

cleanup_cluster() {
job_id=$(echo $1)

git clone https://github.com/openebs/e2e-tests.git
cd e2e-tests

# Replace the VM IP In csv file
sed -i -e 's/10.12.22.10/10.57.1.220/g' \
-e 's/10.12.22.11/10.57.1.221/g' \
-e 's/10.12.22.12/10.57.1.222/g' \
-e 's/10.12.22.13/10.57.1.223/g' k8s/on-prem/openshift-installer/ip.csv

#Replace the Vm names in csv file
sed -i -e 's/auto1/lvm-master/g' \
-e 's/auto2/lvm-node1/g' \
-e 's/auto3/lvm-node2/g' \
-e 's/auto4/lvm-node3/g' k8s/on-prem/openshift-installer/vm_name.csv

#Replace the snapshot name and exp ip in vars
sed -i -e 's/snapshot_name: "oc-cluster"/snapshot_name: "1.21"/g' \
-e 's/esx_ip: "10.12.1.1"/esx_ip: "10.57.1.1"/g' k8s/on-prem/openshift-installer/vars.yml

ansible-playbook k8s/on-prem/openshift-installer/revert_cluster_state.yml -vv

#Removimg e2e nativek8s test repo
cd && rm -rf e2e-nativek8s
}

if [ "$1" == "run_job" ];then
  cleanup_cluster $2
else
  connect_cluster
fi
