#!/bin/bash

## SSH into the cluster to run the kubernetes jobs for the experiments
connect_cluster() {
mkdir -p /root/.ssh
touch /root/.ssh/id_rsa
echo "$SSH_KEYS" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa
ssh -o StrictHostKeyChecking=no $lvm_user@$ip -p $port -i /root/.ssh/id_rsa -o LogLevel=ERROR 'cd e2e-nativek8s && bash pipeline/stages/5-functional/lvm-vol-resize-btrfs run_job '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'

}

###################
#     App-kill    #
###################

app_kill_btrfs() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
source ~/.profile

time="date"
current_time=$(eval $time)

## Create the e2e-result-custom-resources for the jobs
bash pipeline/utils/lvm-e2e-cr jobname:lvm-vol-resize-btrfs jobphase:Waiting
bash pipeline/utils/lvm-e2e-cr jobname:lvm-vol-resize-btrfs jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

## Generate the test name for running the e2e-test for percona deployment
run_id="btrfs";test_name=$(bash pipeline/utils/generate_test_name testcase=application-pod-failure metadata=${run_id})
echo $test_name

## copy the content of run_e2e_test.yml into a temporary file to update the test specific parameters.
cd lvm-localpv/e2e-tests
cp experiments/chaos/app_pod_failure/run_e2e_test.yml appkill.yml

# Modify test specific values in runner file using sed command
sed -i -e '/name: APP_NAMESPACE/{n;s/.*/            value: lvm-resize-btrfs/g}' \
-e '/name: APP_LABEL/{n;s/.*/            value: app=percona/g}' \
-e 's/test: application-pod-failure/test: application-pod-failure-btrfs/g' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/g}' appkill.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' appkill.yml

## Insert the set of variables for percona data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    dbuser: root\
    dbpassword: k8sDem0\
    dbname: appkill
' appkill.yml

cat appkill.yml

bash ../../pipeline/utils/e2e_job_runner label='test:application-pod-failure-btrfs' job=appkill.yml
cd ../..
# Get the cluster state once the e2e-test jobs completed.
bash pipeline/utils/dump_cluster_state;
bash pipeline/utils/event_updater jobname:lvm-vol-resize-btrfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

app_kill_btrfs_rc_val=$(echo $?)
if [ "$app_kill_btrfs_rc_val" != "0" ]; then
exit 1;
fi

}

#############################
# CSI volume resize for lvm #
#############################

lvm_vol_resize_btrfs() {

## Generate the test name for running the litmusbook for percona deployment
run_id="btrfs";test_name=$(bash pipeline/utils/generate_test_name testcase=lvm-volume-resize metadata=${run_id})
echo $test_name

## copy the content of run_e2e_test.yml into a temporary file to update the test specific parameters.
cd lvm-localpv/e2e-tests
cp experiments/functional/lvm-volume-resize/run_e2e_test.yml lvm_resize_btrfs.yml

# Modify test specific values in runner file using sed command
sed -i -e '/name: APP_NAMESPACE/{n;s/.*/            value: lvm-resize-btrfs/g}' \
-e 's/generateName: lvm-vol-resize-/generateName: lvm-vol-resize-btrfs-/g' \
-e 's/app: lvm-vol-resize/app: lvm-vol-resize-btrfs/g' \
-e '/name: APP_PVC/{n;s/.*/            value: percona-pvc/g}' \
-e '/name: APP_LABEL/{n;s/.*/            value: app=percona/g}' \
-e '/name: STORAGE_CLASS/{n;s/.*/            value: openebs-lvmsc-btrfs/g}' \
-e '/name: OLD_PV_CAPACITY/{n;s/.*/            value: 5Gi/g}' \
-e '/name: NEW_PV_CAPACITY/{n;s/.*/            value: 10Gi/g}' lvm_resize_btrfs.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' lvm_resize_btrfs.yml

cat lvm_resize_btrfs.yml

## Run the e2e-test job and get the details of the job from e2e_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='app:lvm-vol-resize-btrfs' job=lvm_resize_btrfs.yml
## Get the cluster state once the e2e job completed.
bash ../../pipeline/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:lvm-vol-resize-btrfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

lvm_vol_resize_btrfs_rc_val=$(echo $?)
if [ "$lvm_vol_resize_btrfs_rc_val" != "0" ]; then
exit 1;
fi

}

#######################################
#   Deprovision percona application   #
#######################################

app_deprovision() {

## Generate test name for running litmusbook for generate load on application
test_name=$(bash pipeline/utils/generate_test_name testcase=percona-deprovision-lvm-resize-btrfs metadata="")
echo $test_name

# copy the content of run_e2e_test.yml into a temporary file to update the test specific parameters.
cd lvm-localpv/e2e-tests
cp apps/percona/deployers/run_e2e_test.yml percona_dep_lvm_resize_btrfs.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/app: percona-deployment/app: percona-deprovision-lvm-resize-btrfs/g' \
-e 's/generateName: percona-deploy-/generateName: percona-deprovision-lvm-resize-btrfs-/g' \
-e "s/value: 'provision'/value: 'deprovision'/g" \
-e "s/value: 'percona'/value: 'lvm-resize-btrfs'/g" percona_dep_lvm_resize_btrfs.yml       

cat percona_dep_lvm_resize_btrfs.yml

## Run the e2e-test job and get the details of the job from e2e_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='app:percona-deprovision-lvm-resize-btrfs' job=percona_dep_lvm_resize_btrfs.yml
cd ../..
## Get the cluster state once the e2e-test job completed.
bash pipeline/utils/dump_cluster_state;
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:lvm-vol-resize-btrfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_deprovision_rc_val=$(echo $?)

if [ "$app_deprovision_rc_val" -eq "0" ]; then

## Update the e2e-result-custom-resources for the job
bash pipeline/utils/lvm-e2e-cr jobname:lvm-vol-resize-btrfs jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Pass

else
## Update the e2e-result-custom-resources for the job
bash pipeline/utils/lvm-e2e-cr jobname:lvm-vol-resize-btrfs jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Fail
exit 1;
fi

}

if [ "$1" == "run_job" ];then
  app_kill_btrfs $2 $3 $4
  lvm_vol_resize_btrfs
  app_deprovision
else
  connect_cluster
fi

