#!/bin/bash

## Define and initialize test-result specific variables.
zfspv_clone_xfs_rc_val=1
zfspv_clone_xfs_deprovision_rc_val=1
zfspv_snapshot_xfs_deprovision_rc_val=1

## SSH into the cluster to run the kubernetes jobs for the experiments
connect_cluster() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $zfs_user@$zfs_ip -p $zfs_port -o LogLevel=ERROR 'cd e2e-nativek8s && bash pipeline/stages/5-functional/zfspv-clone-xfs run_job '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$ZFS_OPERATOR_NAMESPACE'"'

}

###########################
# create zfspv-clone-xfs #
###########################

zfspv_clone_xfs() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
zfs_operator_namespace=$(echo $4)
source ~/.profile

time="date"
current_time=$(eval $time)

## Create the e2e-result-custom-resources for the jobs
bash pipeline/utils/zfs-e2e-cr jobname:clone-xfs jobphase:Waiting
bash pipeline/utils/zfs-e2e-cr jobname:clone-xfs jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

## Generate the test name to run litmusbook for creating zfspv-clone
run_id="xfs";test_name=$(bash pipeline/utils/generate_test_name testcase=zfspv-clone metadata=${run_id})
echo $test_name
cd zfs-localpv/e2e-tests

# copy the content of run_e2e_test.yml into a different file to update the test specific parameters.
cp experiments/functional/zfspv-clone/run_e2e_test.yml clone_xfs.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/generateName: zfspv-clone-/generateName: clone-zfspv-xfs/g' \
-e 's/name: zfspv-snapshot-clone/name: snap-clone-xfs/g' \
-e 's/test: zfspv-clone/test: clone-zfspv-xfs/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: xfs-snap/}' \
-e "/name: ZFS_OPERATOR_NAMESPACE/{n;s/.*/            value: ${zfs_operator_namespace}/}" \
-e '/name: STORAGE_CLASS/{n;s/.*/            value: zfspv-sc-xfs/}' \
-e '/name: SNAPSHOT_NAME/{n;s/.*/            value: xfs-snapshot/}' \
-e '/name: CLONE_PVC_NAME/{n;s/.*/            value: clone-pvc/}' \
-e '/name: APP_NAME/{n;s/.*/            value: percona/}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/}' clone_xfs.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' clone_xfs.yml

cat clone_xfs.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='test:clone-zfspv-xfs' job=clone_xfs.yml
## Get the cluster state Once the litmus jobs completed.
bash ../../pipeline/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:zfspv-snapshot-clone-xfs-create $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

zfspv_clone_xfs_rc_val=$(echo $?)
if [ "$zfspv_clone_xfs_rc_val" != "0" ]; then
exit 1;
fi

}

################################
# Deprovision zfspv-clone-xfs #
################################

zfspv_clone_xfs_deprovision() {

## Generate test name to run litmusbook for deprovisioning the zfspv clone
run_id="xfs-deprovision";test_name=$(bash pipeline/utils/generate_test_name testcase=zfspv-clone metadata=${run_id})
echo $test_name
cd zfs-localpv/e2e-tests

# copy the content of run_e2e_test.yml into a different file to update the test specific parameters.
cp experiments/functional/zfspv-clone/run_e2e_test.yml clone_xfs_deprovision.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/generateName: zfspv-clone-/generateName: clone-xfs-deprovision-/g' \
-e '/labels:/{n;s/  test: zfspv-clone/  test: clone-xfs-deprovision/g}' \
-e 's/name: zfspv-snapshot-clone/name: snap-clone-xfs/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: xfs-snap/}' \
-e "/name: ZFS_OPERATOR_NAMESPACE/{n;s/.*/            value: ${zfs_operator_namespace}/}" \
-e '/name: STORAGE_CLASS/{n;s/.*/            value: zfspv-sc-xfs/}' \
-e '/name: SNAPSHOT_NAME/{n;s/.*/            value: xfs-snapshot/}' \
-e '/name: CLONE_PVC_NAME/{n;s/.*/            value: clone-pvc/}' \
-e '/name: APP_NAME/{n;s/.*/            value: percona/}' \
-e '/name: ACTION/{n;s/.*/            value: deprovision/}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/}' clone_xfs_deprovision.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' clone_xfs_deprovision.yml

cat clone_xfs_deprovision.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='test:clone-xfs-deprovision' job=clone_xfs_deprovision.yml
## Get the cluster state Once the litmus jobs completed.
bash ../../pipeline/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:zfspv-snapshot-clone-xfs-create $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

zfspv_clone_xfs_deprovision_rc_val=$(echo $?)
if [ "$zfspv_clone_xfs_deprovision_rc_val" != "0" ]; then
exit 1;
fi

}

###################################
# Deprovision zfspv-snapshot-xfs #
###################################

zfspv_snapshot_xfs_deprovision() {

## Generate test name to run litmusbook for deprovisioning the zfspv-snapshot
run_id="xfs-deprovision";test_name=$(bash pipeline/utils/generate_test_name testcase=zfspv-snapshot metadata=${run_id})
echo $test_name
cd zfs-localpv/e2e-tests

# copy the content of provisioner run_e2e_test.yml into a different file to update the test specific parameters.
cp experiments/functional/zfspv-snapshot/run_e2e_test.yml snap_xfs_deprovision.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/generateName: zfspv-snapshot-/generateName: snap-xfs-deprovision-/g' \
-e '/labels:/{n;s/  test: zfspv-snapshot/  test: snap-xfs-deprovision/g}' \
-e 's/name: zfspv-snapshot-clone/name: snap-clone-xfs/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: xfs-snap/}' \
-e "/name: ZFS_OPERATOR_NAMESPACE/{n;s/.*/            value: ${zfs_operator_namespace}/}" \
-e '/name: SNAPSHOT_CLASS/{n;s/.*/            value: xfs-snapshot-class/}' \
-e '/name: SNAPSHOT_NAME/{n;s/.*/            value: xfs-snapshot/}' \
-e '/name: APP_PVC/{n;s/.*/            value: percona-pvc/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: app=percona/}' \
-e '/name: ACTION/{n;s/.*/            value: deprovision/}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/}' snap_xfs_deprovision.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' snap_xfs_deprovision.yml

cat snap_xfs_deprovision.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='test:snap-xfs-deprovision' job=snap_xfs_deprovision.yml
## Get the cluster state Once the litmus jobs completed.
bash ../../pipeline/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:zfspv-snapshot-clone-xfs-create $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

zfspv_snapshot_xfs_deprovision_rc_val=$(echo $?)
if [ "$zfspv_snapshot_xfs_deprovision_rc_val" != "0" ]; then
exit 1;
fi

}

###########################
# Deprovision Application #
###########################

app_deprovision_xfs() {
  
## Generate test name to run litmusbook for deprovisioning the percona application
test_name=$(bash pipeline/utils/generate_test_name testcase=percona-deprovision-xfs-snap metadata='')
echo $test_name
cd zfs-localpv/e2e-tests

# copy the content of run_e2e_test.yml into a different file to update the test specific parameters.
cp apps/percona/deployers/run_e2e_test.yml percona_xfs_snap_clone_dep.yml

# Modify test specific values in runner file using sed command
sed -i -e "/name: APP_NAMESPACE/{n;s/value: 'percona'/value: 'xfs-snap'/g}" \
-e 's/app: percona-deployment/app: percona-deprovision-xfs-snap/g' \
-e 's/generateName: percona-deploy-/generateName: percona-deprovision-xfs-snap-/g' \
-e "s/value: 'provision'/value: 'deprovision'/g" percona_xfs_snap_clone_dep.yml

cat percona_xfs_snap_clone_dep.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='app:percona-deprovision-xfs-snap' job=percona_xfs_snap_clone_dep.yml
## Get the cluster state Once the litmus jobs completed.
bash ../../pipeline/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:zfspv-snapshot-clone-xfs-create $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_deprovision_xfs_rc_val=$(echo $?)

if [ "$app_deprovision_xfs_rc_val" -eq "0" ] &&
   [ "$zfspv_snapshot_xfs_deprovision_rc_val" -eq "0" ] &&
   [ "$zfspv_clone_xfs_deprovision_rc_val" -eq "0" ] &&
   [ "$zfspv_clone_xfs_rc_val" -eq "0" ]; then

## Update the e2e-result-custom-resources for the job
bash pipeline/utils/zfs-e2e-cr jobname:clone-xfs jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Pass

else
## Update the e2e-result-custom-resources for the job
bash pipeline/utils/zfs-e2e-cr jobname:clone-xfs jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Fail
exit 1;
fi

}

if [ "$1" == "run_job" ];then
  zfspv_clone_xfs $2 $3 $4 $5
  zfspv_clone_xfs_deprovision
  zfspv_snapshot_xfs_deprovision
  app_deprovision_xfs
else
  connect_cluster
fi