#!/bin/bash

## SSH into the cluster to run the kubernetes jobs for the experiments
connect_cluster() {
mkdir -p /root/.ssh
touch /root/.ssh/id_rsa
echo "$SSH_KEYS" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa
sshpass -p $pass ssh -o StrictHostKeyChecking=no $zfs_user@$zfs_ip -p $zfs_port -i /root/.ssh/id_rsa -o LogLevel=ERROR 'cd e2e-nativek8s && bash pipeline/stages/3-app-deploy/app-zfspv-snapshot-xfs run_job '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$ZFS_OPERATOR_NAMESPACE'"'

}

###########################################################
# Deploy percona application on ZFSPV when fstype is xfs #
###########################################################

app_deploy_xfs() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
zfs_operator_namespace=$(echo $4)
source ~/.profile

time="date"
current_time=$(eval $time)

## Create the e2e-result-custom-resources for the jobs
bash pipeline/utils/zfs-e2e-cr jobname:app-snap-xfs jobphase:Waiting
bash pipeline/utils/zfs-e2e-cr jobname:app-snap-xfs jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

## Generate the test name for running the litmusbook for percona deployment
test_name=$(bash pipeline/utils/generate_test_name testcase=percona-provision-xfs-snap metadata='')
echo $test_name
cd zfs-localpv/e2e-tests

# copy the content of deployers run_e2e_test.yml into a different file to update the test specific parameters.
cp apps/percona/deployers/run_e2e_test.yml percona_xfs_snap_clone.yml

# Modify test specific values in runner file using sed command
sed -i -e "/name: APP_NAMESPACE/{n;s/value: 'percona'/value: 'xfs-snap'/g}" \
-e 's/generateName: percona-deploy-/generateName: percona-provision-xfs-snap-/g' \
-e "/name: STORAGE_CLASS/{n;s/value: 'zfspv-sc'/value: 'zfspv-sc-xfs'/g}" \
-e 's/app: percona-deployment/app: percona-deployment-xfs-snap/g' percona_xfs_snap_clone.yml


cat percona_xfs_snap_clone.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='app:percona-deployment-xfs-snap' job=percona_xfs_snap_clone.yml
## Get the cluster state Once the litmus jobs completed.
bash ../../pipeline/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:app-snap-xfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_deploy_xfs_rc_val=$(echo $?)
if [ "$app_deploy_xfs_rc_val" != "0" ]; then
exit 1;
fi

}

###################################
# Loadgen on Percona application  #
###################################

app_loadgen_xfs() {

## Generate test name for running litmusbook for generate load on application
test_name=$(bash pipeline/utils/generate_test_name testcase=percona-loadgen-xfs-snap metadata='')
echo $test_name
cd zfs-localpv/e2e-tests

# copy the content of workload run_e2e_test.yml into a different file to update the test specific parameters.
cp apps/percona/workload/run_e2e_test.yml loadgen_xfs_snap_clone.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/loadgen: percona-loadjob/loadgen: percona-loadjob-xfs-snap/g' \
-e 's/generateName: percona-loadgen-/generateName: percona-loadgen-xfs-snap-/g' \
-e "/name: APP_NAMESPACE/{n;s/value: 'percona'/value: 'xfs-snap'/g}" loadgen_xfs_snap_clone.yml


cat loadgen_xfs_snap_clone.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='loadgen:percona-loadjob-xfs-snap' job=loadgen_xfs_snap_clone.yml
## Get the cluster state Once the litmus jobs completed.
bash ../../pipeline/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:app-snap-xfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_loadgen_xfs_rc_val=$(echo $?)
if [ "$app_loadgen_xfs_rc_val" != "0" ]; then
exit 1;
fi

}

##############################
# Create zfspv-snapshot-xfs #
##############################

zfspv_snapshot_xfs() { 
  
## Generate test name for running litmusbook for creating zfspv snapshot
run_id="xfs";test_name=$(bash pipeline/utils/generate_test_name testcase=zfspv-snapshot metadata=${run_id})
echo $test_name
cd zfs-localpv/e2e-tests

# copy the content of run_e2e_test.yml into a different file to update the test specific parameters.
cp experiments/functional/zfspv-snapshot/run_e2e_test.yml snap_xfs.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/generateName: zfspv-snapshot-/generateName: snapshot-zfspv-xfs/g' \
-e 's/name: zfspv-snapshot-clone/name: snap-clone-xfs/g' \
-e 's/test: zfspv-snapshot/test: snapshot-xfs/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: xfs-snap/}' \
-e "/name: ZFS_OPERATOR_NAMESPACE/{n;s/.*/            value: ${zfs_operator_namespace}/}" \
-e '/name: SNAPSHOT_CLASS/{n;s/.*/            value: zfs-snapshot-class/}' \
-e '/name: SNAPSHOT_NAME/{n;s/.*/            value: xfs-snapshot/}' \
-e '/name: APP_PVC/{n;s/.*/            value: percona-pvc/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: app=percona/}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/}' snap_xfs.yml

sed -i '/parameters.yml: |/a \
    dbuser: root\
    dbpassword: k8sDem0\
    dbname: snap_clone_xfs
' snap_xfs.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' snap_xfs.yml

cat snap_xfs.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='test:snapshot-xfs' job=snap_xfs.yml
## Get the cluster state Once the litmus jobs completed.
bash ../../pipeline/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:app-snap-xfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

zfspv_snapshot_xfs_rc_val=$(echo $?)
if [ "$zfspv_snapshot_xfs_rc_val" != "0" ]; then
exit 1;
fi

if [ "$zfspv_snapshot_xfs_rc_val" -eq "0" ] &&
   [ "$app_loadgen_xfs_rc_val" -eq "0" ] &&
   [ "$app_deploy_xfs_rc_val" -eq "0" ]; then

## Update the e2e-result-custom-resources for the job
bash pipeline/utils/zfs-e2e-cr jobname:app-snap-xfs jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Pass

fi

}

if [ "$1" == "run_job" ];then
  app_deploy_xfs $2 $3 $4 $5
  app_loadgen_xfs
  zfspv_snapshot_xfs

else
  connect_cluster
fi