#!/bin/bash

## SSH into the cluster to run the kubernetes jobs for the experiments
connect_cluster() {
mkdir -p /root/.ssh
touch /root/.ssh/id_rsa
echo "$SSH_KEYS" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa
sshpass -p $pass ssh -o StrictHostKeyChecking=no $device_user@$device_ip -p $device_port -i /root/.ssh/id_rsa -o LogLevel=ERROR 'cd e2e-nativek8s && bash pipeline/stages/4-chaos/4C01-application-pod-failure-ext4 run_job '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'

}

#######################################
# Deploy percona application on devicePV #
#######################################

app_deploy() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)

time="date"
current_time=$(eval $time)

## Create the e2e-result-custom-resources for the jobs
bash pipeline/utils/device-e2e-cr jobname:application-pod-failure-ext4 jobphase:Waiting
bash pipeline/utils/device-e2e-cr jobname:application-pod-failure-ext4 jobphase:Running init_time:"$current_time" jobid:"$job_id"

## Generate the test name for running the e2e-test for percona deployment
test_name=$(bash pipeline/utils/generate_test_name testcase=percona-provision-app-kill-ext4 metadata="")
echo $test_name

## copy the content of run_e2e_test.yml into a temporary file to update the test specific parameters.
cd device-localpv/e2e-tests
cp apps/percona/deployers/run_e2e_test.yml percona_app_kill_ext4.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/app: percona-deployment/app: percona-deployment-app-kill-ext4/g' \
-e 's/generateName: percona-deploy-/generateName: percona-deploy-app-pod-failure-ext4-/g' \
-e "s/value: 'device-sc-ext4'/value: 'device-sc-ext4-wfc'/g" \
-e "s/value: 'percona'/value: 'app-kill-ext4'/g" percona_app_kill_ext4.yml

cat percona_app_kill_ext4.yml

## Run the e2e-test job and get the details of the job from e2e_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='app:percona-deployment-app-kill-ext4' job=percona_app_kill_ext4.yml
## Get the cluster state once the e2e-test job completed.
bash ../../pipeline/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:application-pod-failure-ext4 $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

app_deploy_rc_val=$(echo $?)
if [ "$app_deploy_rc_val" != "0" ]; then
exit 1;
fi

}

######################
#    App loadgen     #
######################

app_loadgen() {

## Generate test name for running test for generate load on application
test_name=$(bash pipeline/utils/generate_test_name testcase=percona-loadgen-app-kill-ext4 metadata='')
echo $test_name

## copy the content of workload run_e2e_test.yml into a temporary file to update the test specific parameters.
cd device-localpv/e2e-tests
cp apps/percona/workload/run_e2e_test.yml loadgen_app_kill_ext4.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/loadgen: percona-loadjob/loadgen: percona-loadjob-app-kill-ext4/g' \
-e 's/generateName: percona-loadgen-/generateName: percona-loadgen-application-pod-failure-ext4-/g' \
-e "s/value: 'percona'/value: 'app-kill-ext4'/g" loadgen_app_kill_ext4.yml

cat loadgen_app_kill_ext4.yml

## Run the e2e-test job and get the details of the job from e2e_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='loadgen:percona-loadjob-app-kill-ext4' job=loadgen_app_kill_ext4.yml
## Get the cluster state Once the e2e-test jobs completed.
bash ../../pipeline/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:application-pod-failure-ext4 $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

app_loadgen_rc_val=$(echo $?)
if [ "$app_loadgen_rc_val" != "0" ]; then
exit 1;
fi

}

####################
#   App pod kill   #
####################

app_pod_kill() {

run_id="ext4";test_name=$(bash pipeline/utils/generate_test_name testcase=application-pod-failure metadata=${run_id})
echo $test_name

## copy the content of run_e2e_test.yml into a temporary file to update the test specific parameters.
cd device-localpv/e2e-tests
cp experiments/chaos/app_pod_failure/run_e2e_test.yml appkill_ext4.yml

# Modify test specific values in runner file using sed command
sed -i -e '/name: APP_NAMESPACE/{n;s/.*/            value: app-kill-ext4/g}' \
-e '/name: APP_LABEL/{n;s/.*/            value: app=percona/g}' \
-e 's/test: application-pod-failure/test: application-pod-failure-ext4/g' \
-e 's/name: app-pod-failure/name: app-pod-failure-ext4/g' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/g}' appkill_ext4.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' appkill_ext4.yml

## Insert the set of variables for percona data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    dbuser: root\
    dbpassword: k8sDem0\
    dbname: appkill_ext4
' appkill_ext4.yml

cat appkill_ext4.yml

bash ../../pipeline/utils/e2e_job_runner label='test:application-pod-failure-ext4' job=appkill_ext4.yml
cd ../..
# Get the cluster state once the e2e-test jobs completed.
bash pipeline/utils/dump_cluster_state;
bash pipeline/utils/event_updater jobname:application-pod-failure-ext4 $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

app_pod_kill_rc_val=$(echo $?)
if [ "$app_pod_kill_rc_val" != "0" ]; then
exit 1;
fi

}

#######################################
#   Deprovision percona application   #
#######################################

app_deprovision() {

## Generate the test name for running the e2e-test for percona deployment
test_name=$(bash pipeline/utils/generate_test_name testcase=percona-deprovision-app-kill-ext4 metadata="")
echo $test_name

## copy the content of run_e2e_test.yml into a temporary file to update the test specific parameters.
cd device-localpv/e2e-tests
cp apps/percona/deployers/run_e2e_test.yml percona_dep_app_kill_ext4.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/app: percona-deployment/app: percona-deprovision-app-kill-ext4/g' \
-e 's/generateName: percona-deploy-/generateName: percona-deprovision-application-pod-failure-ext4-/g' \
-e "s/value: 'provision'/value: 'deprovision'/g" \
-e "s/value: 'percona'/value: 'app-kill-ext4'/g" percona_dep_app_kill_ext4.yml

cat percona_dep_app_kill_ext4.yml

## Run the e2e-test job and get the details of the job from e2e_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='app:percona-deprovision-app-kill-ext4' job=percona_dep_app_kill_ext4.yml
## Get the cluster state once the e2e-test job completed.
bash ../../pipeline/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:application-pod-failure-ext4 $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

app_deprovision_rc_val=$(echo $?)

if [ "$app_deprovision_rc_val" != "0" ]; then

bash pipeline/utils/device-e2e-cr jobname:application-pod-failure-ext4 jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Fail
exit 1;

fi

## Update the e2e-result-custom-resources for the job
bash pipeline/utils/device-e2e-cr jobname:application-pod-failure-ext4 jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Pass

}

if [ "$1" == "run_job" ];then
  app_deploy $2 $3 $4
  app_loadgen
  app_pod_kill
  app_deprovision
else
  connect_cluster
fi