#!/bin/bash

## Define and initialize test-result specific variables.
app_deploy_rc_val=1
app_loadgen_rc_val=1
app_pod_kill_btrfs_rc_val=1

## SSH into the cluster to run the kubernetes jobs for the experiments
connect_cluster() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $zfs_user@$zfs_ip -p $zfs_port -o LogLevel=ERROR 'cd e2e-nativek8s && bash pipeline/stages/4-chaos/4C04-app-pod-kill-btrfs run_job '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'

}

#######################################
# Deploy percona application on ZFSPV #
#######################################

app_deploy() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

## Pooling over the previous job to wait for its completion
bash pipeline/utils/zfs-e2e-cr jobname:app-pod-kill-btrfs jobphase:Waiting
bash pipeline/utils/zfs-e2e-cr jobname:app-pod-kill-btrfs jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

## Generate the test name for running the litmusbook for percona deployment
test_name=$(bash pipeline/utils/generate_test_name testcase=percona-provision-app-kill-btrfs metadata='')
echo $test_name

## copy the content of provisioner run_e2e_test.yml into a temporary file to update the test specific parameters.
cd zfs-localpv/e2e-tests
cp apps/percona/deployers/run_e2e_test.yml percona_deploy_app_kill_btrfs.yml

# Modify test specific values in runner file using sed command
sed -i -e "/name: APP_NAMESPACE/{n;s/value: 'percona'/value: 'app-kill-btrfs'/g}" \
-e 's/generateName: percona-deploy-/generateName: percona-provision-app-kill-btrfs-/g' \
-e "/name: STORAGE_CLASS/{n;s/value: 'zfspv-sc'/value: 'zfspv-sc-btrfs'/g}" \
-e 's/app: percona-deployment/app: percona-provision-app-kill-btrfs/g' percona_deploy_app_kill_btrfs.yml

cat percona_deploy_app_kill_btrfs.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='app:percona-provision-app-kill-btrfs' job=percona_deploy_app_kill_btrfs.yml
## Get the cluster state Once the litmus jobs completed.
bash ../../pipeline/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:app-pod-kill-btrfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_deploy_rc_val=$(echo $?)
if [ "$app_deploy_rc_val" != "0" ]; then
exit 1;
fi

}

######################
#    App loadgen     #
######################

app_loadgen() {

## Generate test name for running litmusbook for generate load on application
test_name=$(bash pipeline/utils/generate_test_name testcase=percona-loadgen-app-kill-btrfs metadata='')
echo $test_name
cd zfs-localpv/e2e-tests

# copy the content of workload run_e2e_test.yml into a different file to update the test specific parameters.
cp apps/percona/workload/run_e2e_test.yml loadgen_app_kill_btrfs.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/loadgen: percona-loadjob/loadgen: percona-loadjob-app-kill-btrfs/g' \
-e 's/generateName: percona-loadgen-/generateName: percona-loadgen-app-kill-btrfs-/g' \
-e "/name: APP_NAMESPACE/{n;s/value: 'percona'/value: 'app-kill-btrfs'/g}" loadgen_app_kill_btrfs.yml

cat loadgen_app_kill_btrfs.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='loadgen:percona-loadjob-app-kill-btrfs' job=loadgen_app_kill_btrfs.yml
## Get the cluster state Once the litmus jobs completed.
bash ../../pipeline/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:app-pod-kill-btrfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_loadgen_rc_val=$(echo $?)
if [ "$app_loadgen_rc_val" != "0" ]; then
exit 1;
fi

}

####################
#   App pod kill   #
####################

app_pod_kill_btrfs() {

run_id="btrfs";test_name=$(bash pipeline/utils/generate_test_name testcase=application-pod-failure metadata=${run_id})
echo $test_name

cd zfs-localpv/e2e-tests
# copy the content of deployer run_e2e_test.yml into a different file to update the test specific parameters.
cp experiments/chaos/app_pod_failure/run_e2e_test.yml appkill_btrfs.yml

sed -i -e '/name: APP_NAMESPACE/{n;s/.*/            value: app-kill-btrfs/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: app=percona/}' \
-e 's/generateName: application-pod-failure-/generateName: btrfs-application-pod-failure-/g' \
-e 's/name: application-pod-failure/name: application-pod-failure-btrfs/g' \
-e 's/name: app-pod-failure/name: app-pod-failure-btrfs-configmap/g' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/}' appkill_btrfs.yml

## Insert the set of variables for busybox data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    dbuser: root\
    dbpassword: k8sDem0\
    dbname: appkillbtrfs
' appkill_btrfs.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' appkill_btrfs.yml

cat appkill_btrfs.yml

bash ../../pipeline/utils/e2e_job_runner label='name:application-pod-failure-btrfs' job=appkill_btrfs.yml
cd ../..
# Get the cluster state Once the litmus jobs completed.
bash pipeline/utils/dump_cluster_state;
bash pipeline/utils/event_updater jobname:app-pod-kill-btrfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_pod_kill_btrfs_rc_val=$(echo $?)
if [ "$app_pod_kill_btrfs_rc_val" != "0" ]; then
exit 1;
fi

}

#######################################
#   Deprovision percona application   #
#######################################

app_deprovision() {

## Generate test name for running litmusbook for generate load on application
test_name=$(bash pipeline/utils/generate_test_name testcase=percona-deprovision-app-kill-btrfs metadata='')
echo $test_name

# copy the content of workload run_e2e_test.yml into a temporary file to update the test specific parameters.
cd zfs-localpv/e2e-tests
cp apps/percona/deployers/run_e2e_test.yml percona_deprovision_app_kill_btrfs.yml

# Modify test specific values in runner file using sed command
sed -i -e "/name: APP_NAMESPACE/{n;s/value: 'percona'/value: 'app-kill-btrfs'/g}" \
-e 's/app: percona-deployment/app: percona-deprovision-app-kill-btrfs/g' \
-e 's/generateName: percona-deploy-/generateName: percona-deprovision-app-kill-btrfs-/g' \
-e "s/value: 'provision'/value: 'deprovision'/g" percona_deprovision_app_kill_btrfs.yml   

cat percona_deprovision_app_kill_btrfs.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='app:percona-deprovision-app-kill-btrfs' job=percona_deprovision_app_kill_btrfs.yml
cd ../..
## Get the cluster state Once the litmus jobs completed.
bash pipeline/utils/dump_cluster_state;
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:app-pod-kill-btrfs $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_deprovision_rc_val=$(echo $?)

if [ "$app_deprovision_rc_val" -eq "0" ] &&
   [ "$app_pod_kill_btrfs_rc_val" -eq "0" ] &&
   [ "$app_loadgen_rc_val" -eq "0" ] &&
   [ "$app_deploy_rc_val" -eq "0" ]; then

## Update the e2e-result-custom-resources for the job
bash pipeline/utils/zfs-e2e-cr jobname:app-pod-kill-btrfs jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Pass
#python3 openebs-nativek8s/utils/result/result_update.py $job_id 4C04 4-chaos "Kill the application pod container when fstype is btrfs" Pass $pipeline_id "$current_time" $commit_id $gittoken

else
## Update the e2e-result-custom-resources for the job
bash pipeline/utils/zfs-e2e-cr jobname:app-pod-kill-btrfs jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Fail
#python3 openebs-nativek8s/utils/result/result_update.py $job_id 4C04 4-chaos "Kill the application pod container when fstype is btrfs" Fail $pipeline_id "$current_time" $commit_id $gittoken

exit 1;
fi

}

if [ "$1" == "run_job" ];then
  app_deploy $2 $3 $4
  app_loadgen
  app_pod_kill_btrfs
  app_deprovision
else
  connect_cluster
fi
