#!/bin/bash

## SSH into the cluster to run the kubernetes jobs for the experiments
connect_cluster() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port -o LogLevel=ERROR 'cd e2e-nativek8s && bash openebs-nativek8s/pipelines/stages/4-upgrade/upgrade-zfslocalpv run_job '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$TO_VERSION_ZFS_BRANCH'"' '"'$TO_VERSION_ZFS_DRIVER_IMAGE'"'

}

#######################################
#    Deploy ZFS LocalPV provisioner   #
#######################################

run_job() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
to_version_zfs_branch=$(echo $4)
to_version_zfs_driver_image=$(echo $5)
source ~/.profile

time="date"
current_time=$(eval $time)

## Create the e2e-result-custom-resources for the jobs
bash openebs-nativek8s/utils/e2e-cr jobname:upgrade-zfslocalpv jobphase:Waiting
bash openebs-nativek8s/utils/e2e-cr jobname:upgrade-zfslocalpv jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

## Generate the test name for running the litmusbook for upgrade zfs-localpv
test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=zfs-localpv-upgrade metadata="")
echo $test_name

# copy the content of upgrade run_litmus_test.yml into a temporary file to update the test specific parameters.
cd e2e-tests
cp experiments/zfs-localpv/upgrade-zfs-localpv/run_litmus_test.yml upgrade.yml

# Modify test specific values in runner file using sed command
sed -i -e "/name: TO_VERSION_ZFS_BRANCH/{n;s/.*/            value: ${to_version_zfs_branch}/g}" \
-e "/name: TO_VERSION_ZFS_DRIVER_IMAGE/{n;s/.*/            value: ${to_version_zfs_driver_image}/g}" \
-e '/name: OPERATOR_NAMESPACE/{n;s/.*/            value: openebs/g}' upgrade.yml

cat upgrade.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='name:zfs-localpv-upgrade' job=upgrade.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:upgrade-zfslocalpv $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

#################
## GET RESULT  ##
#################

rc_val=$(echo $?)

source ~/.profile
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash openebs-nativek8s/utils/e2e-cr jobname:upgrade-zfslocalpv jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:$testResult

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "run_job" ];then
  run_job $2 $3 $4 $5 $6
else
  connect_cluster
fi