#!/bin/bash
set -x
pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-nativek8s && bash openebs-nativek8s/pipelines/stages/3-functional/ZFS-LocalPV-provisioner/ZFS-LocalPV-provisioner node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'

}

node() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

echo "*******Deploy ZFS PV provisioner**************"

bash openebs-nativek8s/utils/e2e-cr jobname:s3-j1-zfs-pv-provisioner jobphase:Waiting
bash openebs-nativek8s/utils/e2e-cr jobname:s3-j2-zfs-volume-provision-percona jobphase:Waiting
bash openebs-nativek8s/utils/e2e-cr jobname:s3-j1-zfs-pv-provisioner jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=zfspv-provisioner metadata="")
echo $test_name
cd litmus

# copy the content of provisioner run_litmus_test.yml into a different file to update the test specific parameters.
cp providers/zfs-localpv-provisioner/run_litmus_test.yml zfs_pv_provisioner.yml

# Modify test specific values in runner file using sed command
sed -i -e '/name: STORAGE_CLASS/{n;s/.*/            value: zfs-sc/g}' \
-e '/name: POOL_NAME/{n;s/.*/            value: zfs-test-pool/g}' \
-e '/name: FILE_SYSTEM/{n;s/.*/            value: zfs/g}' \
-e '/name: POOL_TYPE/{n;s/.*/            value: stripe/g}' \
-e '/name: ACTION/{n;s/.*/            value: provision/g}' \
-e '/name: COMPRESSION/{n;s/.*/            value: off/g}' \
-e '/name: DEDUP/{n;s/.*/            value: off/g}' \
-e '/name: RECORDSIZE/{n;s/.*/            value: 4k/g}' zfs_pv_provisioner.yml

cat zfs_pv_provisioner.yml

bash ../openebs-nativek8s/utils/litmus_job_runner label='name:openebs-zfspv-provision' job=zfs_pv_provisioner.yml
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
bash openebs-nativek8s/utils/event_updater jobname:s3-j1-zfs-pv-provisioner $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

#################
## GET RESULT  ##
#################

rc_val=$(echo $?)

source ~/.profile
gittoken=$(echo "$github_token")
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash openebs-nativek8s/utils/e2e-cr jobname:s3-j1-zfs-pv-provisioner jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:$testResult

python3 openebs-nativek8s/utils/result/result_update.py $job_id 3-functional "Deploy ZFS-LocalPV provisioner and corresponding storage class" $testResult $pipeline_id "$current_time" $commit_id $gittoken
if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi

