#!/bin/bash

### Taint the node to run infra chaos test scripts
node_name=$(sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port -o LogLevel=ERROR kubectl get nodes --no-headers | grep -v master | awk 'FNR==1 {print $1}')

## Define and initialize test-result specific variables.
app_deploy_rc_val=1
app_loadgen_rc_val=1
zfs_kubelet_restart_rc_val=1

## SSH into the cluster to run the kubernetes jobs for the experiments
connect_cluster() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port -o LogLevel=ERROR 'cd e2e-nativek8s && bash openebs-nativek8s/pipelines/stages/4-infra-chaos/kubelet-restart/kubelet-restart run_job '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$node_name'"'

}

#######################################
# Deploy percona application on ZFSPV #
#######################################

app_deploy() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
observer_node=$4
source ~/.profile

time="date"
current_time=$(eval $time)

## Pooling over the previous job to wait for its completion
bash openebs-nativek8s/utils/pooling jobname:zfs-docker-restart
bash openebs-nativek8s/utils/e2e-cr jobname:zfs-kubelet-restart jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

## Generate the test name for running the litmusbook for percona deployment
run_id="zfs-kubelet";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=percona-deployment metadata=${run_id})
echo $test_name

## copy the content of provisioner run_litmus_test.yml into a temporary file to update the test specific parameters.
cd e2e-tests
cp apps/percona/deployers/run_litmus_test.yml percona_zfs_kubelet.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/app: percona-deployment/app: percona-zfs-kubelet/g' \
-e 's/generateName: litmus-percona-/generateName: percona-zfs-kubelet-restart-/g' \
-e 's/value: openebs-standard/value: zfs-sc-zfs/g' \
-e '/name: TARGET_AFFINITY_CHECK/{n;s/value: enable/value: disable/g}' \
-e 's/value: app-percona-ns/value: percona-zfs-kubelet/g' percona_zfs_kubelet.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' percona_zfs_kubelet.yml

cat percona_zfs_kubelet.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='app:percona-zfs-kubelet' job=percona_zfs_kubelet.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfs-kubelet-restart $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_deploy_rc_val=$(echo $?)
if [ "$app_deploy_rc_val" != "0" ]; then
exit 1;
fi

}

###################################
# Loadgen on Percona application  #
###################################

app_loadgen() {

## Generate test name for running litmusbook for generate load on application
run_id="zfs-kubelet";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=percona-loadgen metadata=${run_id})
echo $test_name
cd e2e-tests

# copy the content of workload run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/percona/workload/run_litmus_test.yml loadgen_zfs_kubelet.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/loadgen: percona-loadjob/loadgen: loadjob-zfs-kubelet/g' \
-e 's/generateName: percona-loadgen-/generateName: loadgen-zfs-kubelet-restart-/g' \
-e 's/value: app-percona-ns/value: percona-zfs-kubelet/g' loadgen_zfs_kubelet.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' loadgen_zfs_kubelet.yml

cat loadgen_zfs_kubelet.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='loadgen:loadjob-zfs-kubelet' job=loadgen_zfs_kubelet.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfs-kubelet-restart $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_loadgen_rc_val=$(echo $?)
if [ "$app_loadgen_rc_val" != "0" ]; then
app_deploy
fi

}

##################################
#  Perform kubelet-restart test   #
##################################

zfs_kubelet_restart() {

## Generate the test name for running the litmusbook for percona deployment
run_id="zfs-kubelet";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=svc-failure-chaos metadata=${run_id})
echo $test_name

## copy the content of run_litmus_test.yml into a temporary file to update the test specific parameters.
cd e2e-tests
cp experiments/chaos/kubernetes/service_failure/run_litmus_test.yml run_zfs_kubelet_restart.yml

# Modify test specific values in runner file using sed command
sed -i -e '/name: OPERATOR_NAMESPACE/{n;s/.*/            value: openebs/g}' \
-e 's/name: svc-failure-chaos/name: zfs-kubelet-restart/g' \
-e 's/generateName: svc-failure-chaos-/generateName: zfs-kubelet-svc-restart-/g' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: percona-zfs-kubelet/g}' \
-e '/name: APP_LABEL/{n;s/.*/            value: name=percona/g}' \
-e '/name: APP_PVC/{n;s/.*/            value: percona-mysql-claim/g}' \
-e '/name: SVC_TYPE/{n;s/.*/            value: kubelet/g}' \
-e 's/password:/password: VGVzdEAxMjM=/g' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/}' run_zfs_kubelet_restart.yml

sed -i -e "s|#nodeSelector|nodeSelector|g" \
-e "s|#  kubernetes.io/hostname:|  kubernetes.io/hostname: ${observer_node}|g" run_zfs_kubelet_restart.yml

sed -i '/parameters.yml: |/a \
    dbuser: root\
    dbpassword: k8sDem0\
    dbname: zfs_kubelet_restart
' run_zfs_kubelet_restart.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_zfs_kubelet_restart.yml

cat run_zfs_kubelet_restart.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='name:zfs-kubelet-restart' job=run_zfs_kubelet_restart.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfs-kubelet-restart $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

zfs_kubelet_restart_rc_val=$(echo $?)
if [ "$zfs_kubelet_restart_rc_val" != "0" ]; then
app_deprovision
fi

}

##########################
# Deprovision Application#
##########################

app_deprovision() {
  
## Generate test name to run litmusbook for deprovisioning the percona application
run_id="dep-zfs-kubelet";test_name=$(bash openebs-nativek8s/utils/generate_test_name testcase=percona-deployment metadata=${run_id})
echo $test_name
cd e2e-tests

# copy the content of run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/percona/deployers/run_litmus_test.yml percona_zfs_kubelet_deprovision.yml

# Modify test specific values in runner file using sed command
sed -i -e 's/app: percona-deployment/app: percona-zfs-kubelet-dep/g' \
-e 's/generateName: litmus-percona-/generateName: percona-zfs-kubelet-dep-/g' \
-e 's/value: openebs-standard/value: zfs-sc-zfs/g' \
-e 's/value: provision/value: deprovision/g' \
-e '/name: TARGET_AFFINITY_CHECK/{n;s/value: enable/value: disable/g}' \
-e 's/value: app-percona-ns/value: percona-zfs-kubelet/g' percona_zfs_kubelet_deprovision.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' percona_zfs_kubelet_deprovision.yml

cat percona_zfs_kubelet_deprovision.yml

## Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../openebs-nativek8s/utils/litmus_job_runner label='app:percona-zfs-kubelet-dep' job=percona_zfs_kubelet_deprovision.yml
## Get the cluster state Once the litmus jobs completed.
bash ../openebs-nativek8s/utils/dump_cluster_state;
cd ..
## Update the e2e event for the job.
bash openebs-nativek8s/utils/event_updater jobname:zfs-kubelet-restart $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

app_deprovision_rc_val=$(echo $?)

if [ "$app_deprovision_rc_val" -eq "0" ] &&
   [ "$zfs_kubelet_restart_rc_val" -eq "0" ] &&
   [ "$app_loadgen_rc_val" -eq "0" ] &&
   [ "$app_deploy_rc_val" -eq "0" ]; then

## Update the e2e-result-custom-resources for the job
bash openebs-nativek8s/utils/e2e-cr jobname:zfs-kubelet-restart jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Pass

else
## Update the e2e-result-custom-resources for the job
bash openebs-nativek8s/utils/e2e-cr jobname:zfs-kubelet-restart jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Fail
exit 1;
fi

}


if [ "$1" == "run_job" ];then
  app_deploy $2 $3 $4 $5
  app_loadgen
  zfs_kubelet_restart
  app_deprovision
else
  connect_cluster
fi