#!/bin/bash

current_time="$(date)"
echo $current_time

echo "***Checking the cluster is Engaged or not***"

state="sshpass -p $pass ssh -o StrictHostKeyChecking=no $lvm_user@$ip -p $port -o LogLevel=ERROR 'ls | grep e2e-nativek8s'"
cluster_state=$(eval $state)

while [ "${cluster_state}" == "e2e-nativek8s" ]; do
  echo "***cluster is Engaged******"
  wait=1
  cluster_state=$(eval $state)
  sleep 30
done

if [ "$wait" == "1" ]; then
sleep 120
fi

echo "***Checking the Cluster's Health***"

echo "***Checking for the number of nodes in ready state***"
ready_nodes=$(sshpass -p $pass ssh -o StrictHostKeyChecking=no $lvm_user@$ip -p $port kubectl get nodes --no-headers | grep -v NotReady | wc -l)

if [ "$ready_nodes" -eq 4 ]; then
echo "Number of nodes in ready state is $ready_nodes"
echo "***Cluster is in Healthy state***"

echo "***Dumping cluster state***"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $lvm_user@$ip -p $port kubectl get nodes
sshpass -p $pass ssh -o StrictHostKeyChecking=no $lvm_user@$ip -p $port kubectl get pods --all-namespaces

echo "***Cloning e2e-nativek8s repo***"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $lvm_user@$ip -p $port 'git clone -b lvm-localpv https://github.com/mayadata-io/e2e-nativek8s.git'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $lvm_user@$ip -p $port 'cd e2e-nativek8s && git clone https://github.com/openebs/lvm-localpv.git'

echo "***Applying the e2e-CRD's yaml***"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $lvm_user@$ip -p $port 'cd e2e-nativek8s/lvm-localpv && kubectl apply -f ./utils/e2e-crd.yml'

echo "***Applying rbac and crds yaml***"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $lvm_user@$ip -p $port 'cd e2e-nativek8s/e2e-tests/hack && kubectl apply -f rbac.yaml && kubectl apply -f crds.yaml'

echo "***Copying kube config for e2e-tests in e2e namespace***"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $lvm_user@$ip -p $port 'cp ~/.kube/config admin.conf && kubectl create cm kubeconfig --from-file=admin.conf -n e2e'

echo "***Updating the test result in the readme***"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $lvm_user@$ip -p $port 'python3 e2e-nativek8s/lvm-localpv/utils/result/result_update.py '"'$CI_JOB_ID'"' 1S01 1-cluster-setup "Configure the cluster and get it ready" Pass '"'$CI_PIPELINE_ID'"' '"'$current_time'"' '"'$CI_COMMIT_SHA'"' '"'$gittoken'"''

else
echo "All nodes are not ready"
echo "***Cluster is in Unhealthy state***"
echo "***cloning e2e-nativek8s repo***"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $lvm_user@$ip -p $port 'git clone -b lvm-localpv https://github.com/mayadata-io/e2e-nativek8s.git'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $lvm_user@$ip -p $port 'python3 e2e-nativek8s/lvm-localpv/utils/result/result_update.py '"'$CI_JOB_ID'"' 1S01 1-cluster-setup "Configure the cluster and get it ready" Fail '"'$CI_PIPELINE_ID'"' '"'$current_time'"' '"'$CI_COMMIT_SHA'"' '"'$gittoken'"''
exit 1;
fi