#!/bin/bash

current_time="$(date)"
echo $current_time

echo "***Checking the cluster is Engaged or not***"

mkdir -p /root/.ssh
touch /root/.ssh/id_rsa
echo "$SSH_KEYS" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa

state="ssh -o StrictHostKeyChecking=no $zfs_user@$zfs_ip -p $zfs_port -i /root/.ssh/id_rsa -o LogLevel=ERROR 'ls | grep e2e-nativek8s'"
cluster_state=$(eval $state)

while [ "${cluster_state}" == "e2e-nativek8s" ]; do
  echo "***cluster is Engaged******"
  wait=1
  cluster_state=$(eval $state)
  sleep 30
done

if [ "$wait" == "1" ]; then
sleep 120
fi

echo "***Checking the Cluster's Health***"

echo "***Checking for the number of nodes in ready state***"
ready_nodes=$(ssh -o StrictHostKeyChecking=no $zfs_user@$zfs_ip -p $zfs_port -i /root/.ssh/id_rsa kubectl get nodes --no-headers | grep -v NotReady | wc -l)

git_token=$(ssh -o StrictHostKeyChecking=no $zfs_user@$zfs_ip -p $zfs_port -i /root/.ssh/id_rsa 'cat ~/.profile | grep github_token | cut -d= -f2')
gittoken=$(echo $git_token | tr -d '"')

if [ "$ready_nodes" -eq $zfs_ready_nodes ]; then
echo "Number of nodes in ready state is $ready_nodes"
echo "***Cluster is in Healthy state***"

echo "***Dumping cluster state***"
ssh -o StrictHostKeyChecking=no $zfs_user@$zfs_ip -p $zfs_port -i /root/.ssh/id_rsa kubectl get nodes
ssh -o StrictHostKeyChecking=no $zfs_user@$zfs_ip -p $zfs_port -i /root/.ssh/id_rsa kubectl get pods --all-namespaces

echo "***Cloning e2e-nativek8s repo***"
ssh -o StrictHostKeyChecking=no $zfs_user@$zfs_ip -p $zfs_port -i /root/.ssh/id_rsa 'git clone -b release-branch https://github.com/mayadata-io/e2e-nativek8s.git'
ssh -o StrictHostKeyChecking=no $zfs_user@$zfs_ip -p $zfs_port -i /root/.ssh/id_rsa 'cd e2e-nativek8s && git clone https://github.com/openebs/zfs-localpv.git'

echo "***Applying the e2e-CRD's yaml***"
ssh -o StrictHostKeyChecking=no $zfs_user@$zfs_ip -p $zfs_port -i /root/.ssh/id_rsa 'cd e2e-nativek8s/pipeline && kubectl apply -f ./utils/zfs-e2e-crd.yml'

echo "***Applying rbac and crds yaml***"
ssh -o StrictHostKeyChecking=no $zfs_user@$zfs_ip -p $zfs_port -i /root/.ssh/id_rsa 'cd e2e-nativek8s/zfs-localpv/e2e-tests/hack && kubectl apply -f rbac.yaml && kubectl apply -f crds.yaml'

echo "***Copying kube config for e2e-tests in litmus namespace***"
ssh -o StrictHostKeyChecking=no $zfs_user@$zfs_ip -p $zfs_port -i /root/.ssh/id_rsa 'cp ~/.kube/config admin.conf && kubectl create cm kubeconfig --from-file=admin.conf -n e2e'

echo "***Updating the test result in the readme***"
#ssh -o StrictHostKeyChecking=no $zfs_user@$zfs_ip -p $zfs_port -i /root/.ssh/id_rsa 'python3 e2e-nativek8s/openebs-nativek8s/utils/result/result_update.py '"'$CI_JOB_ID'"' 1S01 1-cluster-setup "Configure the cluster and get it ready" Pass '"'$CI_PIPELINE_ID'"' '"'$current_time'"' '"'$CI_COMMIT_SHA'"' '"'$gittoken'"''

else
echo "All nodes are not ready"
echo "***Cluster is in Unhealthy state***"
echo "***cloning e2e-nativek8s repo***"
ssh -o StrictHostKeyChecking=no $zfs_user@$zfs_ip -p $zfs_port -i /root/.ssh/id_rsa 'git clone -b release-branch https://github.com/mayadata-io/e2e-nativek8s.git'
#ssh -o StrictHostKeyChecking=no $zfs_user@$zfs_ip -p $zfs_port -i /root/.ssh/id_rsa 'python3 e2e-nativek8s/openebs-nativek8s/utils/result/result_update.py '"'$CI_JOB_ID'"' 1S01 1-cluster-setup "Configure the cluster and get it ready" Fail '"'$CI_PIPELINE_ID'"' '"'$current_time'"' '"'$CI_COMMIT_SHA'"' '"'$gittoken'"''
exit 1;
fi
