#!/bin/bash

current_time="$(date)"
echo $current_time

echo "***Checking the cluster is Engaged or not***"

state="sshpass -p $pass ssh -o StrictHostKeyChecking=no $device_user@$device_ip -p $device_port -o LogLevel=ERROR 'ls | grep e2e-nativek8s'"
cluster_state=$(eval $state)

while [ "${cluster_state}" == "e2e-nativek8s" ]; do
  echo "***cluster is Engaged******"
  wait=1
  cluster_state=$(eval $state)
  sleep 30
done

if [ "$wait" == "1" ]; then
sleep 120
fi

echo "***Checking the Cluster's Health***"

echo "***Checking for the number of nodes in ready state***"
ready_nodes=$(sshpass -p $pass ssh -o StrictHostKeyChecking=no $device_user@$device_ip -p $device_port kubectl get nodes --no-headers | grep -v NotReady | wc -l)

if [ "$ready_nodes" -eq $device_ready_nodes ]; then
echo "Number of nodes in ready state is $ready_nodes"
echo "***Cluster is in Healthy state***"

echo "***Dumping cluster state***"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $device_user@$device_ip -p $device_port kubectl get nodes
sshpass -p $pass ssh -o StrictHostKeyChecking=no $device_user@$device_ip -p $device_port kubectl get pods --all-namespaces

echo "***Cloning e2e-nativek8s repo***"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $device_user@$device_ip -p $device_port 'git clone -b device-localpv https://github.com/mayadata-io/e2e-nativek8s.git'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $device_user@$device_ip -p $device_port 'cd e2e-nativek8s && git clone https://github.com/openebs/device-localpv.git'

echo "***Applying the e2e-CRD's yaml***"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $device_user@$device_ip -p $device_port 'cd e2e-nativek8s/pipeline && kubectl apply -f ./utils/device-e2e-crd.yml'

echo "***Applying rbac and crds yaml***"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $device_user@$device_ip -p $device_port 'cd e2e-nativek8s/device-localpv/e2e-tests/hack && kubectl apply -f rbac.yaml && kubectl apply -f crds.yaml'

echo "***Copying kube config for e2e-tests in e2e namespace***"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $device_user@$device_ip -p $device_port 'cp ~/.kube/config admin.conf && kubectl create cm kubeconfig --from-file=admin.conf -n e2e'

else
echo "All nodes are not ready"
echo "***Cluster is in Unhealthy state***"
echo "***cloning e2e-nativek8s repo***"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $device_user@$device_ip -p $device_port 'git clone -b device-localpv https://github.com/mayadata-io/e2e-nativek8s.git'
exit 1;
fi