#!/bin/bash

## SSH into the cluster to run the kubernetes jobs for the experiments
connect_cluster() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $lvm_user@$ip -p $port -o LogLevel=ERROR 'cd e2e-nativek8s && bash pipeline/stages/2-provisioner/2P02-lvm-controller-high-availability run_job '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$LVM_OPERATOR_NAMESPACE'"'

}

#######################################
#     Scale LVM LocalPV Controller    #
#######################################

run_job() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
lvm_operator_ns=$(echo $4)

time="date"
current_time=$(eval $time)

## Pooling over the previous job to wait for its completion
bash pipeline/utils/pooling jobname:lvm-localpv-provisioner
bash pipeline/utils/e2e-cr jobname:lvm-ctrl-high-availability jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

## Generate the test name for running the e2e-test for scaling the lvm-controller
test_name=$(bash pipeline/utils/generate_test_name testcase=lvm-controller-high-availability metadata="")
echo $test_name

## copy the content of run_e2e_test.yml into a temporary file to update the test specific parameters.
cd lvm-localpv/e2e-tests
cp experiments/functional/lvm-controller-high-availability/run_e2e_test.yml lvm_ctrl_HA.yml

# copy the content of provisioner run_e2e_test.yml into a temporary file to update the test specific parameters.
sed -i -e "/name: OPERATOR_NAMESPACE/{n;s/.*/            value: ${lvm_operator_ns}/g}" \

cat lvm_ctrl_HA.yml

## Run the e2e-test job and get the details of the job from e2e_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='name:lvm-controller-high-availability' job=lvm_ctrl_HA.yml
## Get the cluster state once the e2e job completed.
bash ../../pipeline/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:lvm-ctrl-high-availability $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

#################
## GET RESULT  ##
#################

rc_val=$(echo $?)

testResult=$(kubectl get e2eresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash pipeline/utils/e2e-cr jobname:lvm-ctrl-high-availability jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:$testResult

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "run_job" ];then
  run_job $2 $3 $4 $5
else
  connect_cluster
fi