#!/bin/bash

## SSH into the cluster to run the kubernetes jobs for the experiments
connect_cluster() {
mkdir -p /root/.ssh
touch /root/.ssh/id_rsa
echo "$SSH_KEYS" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa
ssh -o StrictHostKeyChecking=no $device_user@$device_ip -i /root/.ssh/id_rsa -o LogLevel=ERROR 'cd e2e-nativek8s && bash pipeline/stages/2-provisioner/2P02-device-controller-high-availability run_job '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$DEVICE_OPERATOR_NAMESPACE'"'

}

#######################################
#     Scale device LocalPV Controller    #
#######################################

run_job() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
device_operator_ns=$(echo $4)

time="date"
current_time=$(eval $time)

## Pooling over the previous job to wait for its completion
bash pipeline/utils/pooling jobname:device-localpv-provisioner
bash pipeline/utils/device-e2e-cr jobname:device-ctrl-high-availability jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

## Generate the test name for running the e2e-test for scaling the device-controller
test_name=$(bash pipeline/utils/generate_test_name testcase=device-controller-high-availability metadata="")
echo $test_name

## copy the content of run_e2e_test.yml into a temporary file to update the test specific parameters.
cd device-localpv/e2e-tests
cp experiments/functional/device-controller-high-availability/run_e2e_test.yml device_ctrl_HA.yml

# copy the content of provisioner run_e2e_test.yml into a temporary file to update the test specific parameters.
sed -i -e "/name: DEVICE_OPERATOR_NAMESPACE/{n;s/value: 'openebs'/value: ${device_operator_ns}/g}" device_ctrl_HA.yml

cat device_ctrl_HA.yml

## Run the e2e-test job and get the details of the job from e2e_job_runner utils.
bash ../../pipeline/utils/e2e_job_runner label='test:device-controller-high-availability' job=device_ctrl_HA.yml
## Get the cluster state once the e2e job completed.
bash ../../pipeline/utils/dump_cluster_state;
cd ../..
## Update the e2e event for the job.
bash pipeline/utils/event_updater jobname:device-ctrl-high-availability $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

#################
## GET RESULT  ##
#################

rc_val=$(echo $?)

testResult=$(kubectl get e2eresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash pipeline/utils/device-e2e-cr jobname:device-ctrl-high-availability jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:$testResult

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "run_job" ];then
  run_job $2 $3 $4 $5
else
  connect_cluster
fi